/** Map district/borough/neighbourhood names to the canonical city TGX can resolve.
 *  Keyed by ISO-2 countryCode → { subName (lowercase) → canonicalCity }.
 *  Used in both autocomplete (to remap district suggestions) and the stream route
 *  (as a safety-net for direct API calls that bypass the autocomplete). */
export const CITY_ALIASES: Record<string, Record<string, string>> = {
    // ── North America ──────────────────────────────────────────────────────────
    US: {
        // New York City
        'manhattan': 'New York', 'brooklyn': 'New York', 'queens': 'New York',
        'bronx': 'New York', 'the bronx': 'New York', 'staten island': 'New York',
        'harlem': 'New York', 'lower east side': 'New York', 'tribeca': 'New York',
        'greenwich village': 'New York', 'east village': 'New York', 'west village': 'New York',
        'williamsburg': 'New York', 'dumbo': 'New York', 'red hook': 'New York',
        'park slope': 'New York', 'crown heights': 'New York', 'bed-stuy': 'New York',
        'bushwick': 'New York', 'astoria': 'New York', 'long island city': 'New York',
        'flushing': 'New York', 'upper east side': 'New York', 'upper west side': 'New York',
        'midtown': 'New York', 'chelsea': 'New York', "hell's kitchen": 'New York',
        'financial district': 'New York', 'battery park': 'New York', 'soho': 'New York',
        'noho': 'New York', 'nolita': 'New York', 'murray hill': 'New York',
        'gramercy': 'New York', 'flatiron': 'New York', 'kips bay': 'New York',
        'inwood': 'New York', 'washington heights': 'New York', 'morningside heights': 'New York',
        'riverdale': 'New York', 'flatbush': 'New York', 'coney island': 'New York',
        'bensonhurst': 'New York', 'sunset park': 'New York', 'bay ridge': 'New York',
        'ridgewood': 'New York', 'jackson heights': 'New York', 'jamaica': 'New York',
        // Los Angeles
        'hollywood': 'Los Angeles', 'beverly hills': 'Los Angeles', 'santa monica': 'Los Angeles',
        'venice': 'Los Angeles', 'west hollywood': 'Los Angeles', 'culver city': 'Los Angeles',
        'malibu': 'Los Angeles', 'brentwood': 'Los Angeles', 'bel air': 'Los Angeles',
        'westwood': 'Los Angeles', 'century city': 'Los Angeles', 'downtown la': 'Los Angeles',
        'arts district': 'Los Angeles', 'echo park': 'Los Angeles', 'silver lake': 'Los Angeles',
        'los feliz': 'Los Angeles', 'koreatown': 'Los Angeles', 'studio city': 'Los Angeles',
        'sherman oaks': 'Los Angeles', 'burbank': 'Los Angeles', 'glendale': 'Los Angeles',
        'pasadena': 'Los Angeles', 'pacific palisades': 'Los Angeles', 'playa vista': 'Los Angeles',
        'manhattan beach': 'Los Angeles', 'redondo beach': 'Los Angeles', 'hermosa beach': 'Los Angeles',
        'long beach': 'Los Angeles', 'inglewood': 'Los Angeles',
        // Chicago
        'magnificent mile': 'Chicago', 'wicker park': 'Chicago', 'lincoln park': 'Chicago',
        'the loop': 'Chicago', 'river north': 'Chicago', 'streeterville': 'Chicago',
        'gold coast chicago': 'Chicago', 'old town chicago': 'Chicago', 'lakeview': 'Chicago',
        'wrigleyville': 'Chicago', 'bucktown': 'Chicago', 'logan square': 'Chicago',
        'pilsen': 'Chicago', 'hyde park chicago': 'Chicago', 'bridgeport': 'Chicago',
        'andersonville': 'Chicago', 'rogers park': 'Chicago', 'ukranian village': 'Chicago',
        // San Francisco
        'the mission': 'San Francisco', 'fishermans wharf': 'San Francisco',
        'haight ashbury': 'San Francisco', 'castro': 'San Francisco',
        'soma': 'San Francisco', 'financial district sf': 'San Francisco',
        'nob hill sf': 'San Francisco', 'pacific heights': 'San Francisco',
        'noe valley': 'San Francisco', 'sunset sf': 'San Francisco',
        'richmond sf': 'San Francisco', 'tenderloin': 'San Francisco',
        'civic center sf': 'San Francisco', 'presidio': 'San Francisco',
        'marina sf': 'San Francisco', 'dogpatch': 'San Francisco',
        'potrero hill': 'San Francisco', 'bernal heights': 'San Francisco',
        // Miami
        'miami beach': 'Miami', 'south beach': 'Miami', 'brickell': 'Miami',
        'wynwood': 'Miami', 'little havana': 'Miami', 'coconut grove': 'Miami',
        'downtown miami': 'Miami', 'edgewater miami': 'Miami', 'midtown miami': 'Miami',
        'design district miami': 'Miami', 'coral gables': 'Miami', 'key biscayne': 'Miami',
        'aventura': 'Miami', 'bal harbour': 'Miami', 'surfside': 'Miami',
        // Washington DC
        'national mall': 'Washington DC', 'capitol hill': 'Washington DC',
        'georgetown': 'Washington DC', 'dupont circle': 'Washington DC',
        'adams morgan': 'Washington DC', 'columbia heights dc': 'Washington DC',
        'logan circle': 'Washington DC', 'navy yard': 'Washington DC',
        'shaw dc': 'Washington DC', 'u street': 'Washington DC',
        'woodley park': 'Washington DC', 'foggy bottom': 'Washington DC',
        'farragut': 'Washington DC', 'anacostia': 'Washington DC',
        // Boston
        'back bay': 'Boston', 'beacon hill': 'Boston', 'south end boston': 'Boston',
        'north end boston': 'Boston', 'cambridge': 'Boston', 'somerville': 'Boston',
        'fenway': 'Boston', 'allston': 'Boston', 'brighton': 'Boston',
        'jamaica plain': 'Boston', 'charlestown boston': 'Boston', 'south boston': 'Boston',
        'east boston': 'Boston', 'roxbury': 'Boston', 'dorchester': 'Boston',
        // Seattle
        'capitol hill seattle': 'Seattle', 'belltown': 'Seattle', 'pioneer square seattle': 'Seattle',
        'fremont seattle': 'Seattle', 'ballard': 'Seattle', 'queen anne': 'Seattle',
        'south lake union': 'Seattle', 'wallingford': 'Seattle', 'university district seattle': 'Seattle',
        'green lake': 'Seattle', 'columbia city': 'Seattle', 'beacon hill seattle': 'Seattle',
        // New Orleans
        'french quarter': 'New Orleans', 'garden district': 'New Orleans', 'marigny': 'New Orleans',
        'treme': 'New Orleans', 'bywater': 'New Orleans', 'uptown new orleans': 'New Orleans',
        'mid-city new orleans': 'New Orleans', 'algiers': 'New Orleans',
        // Las Vegas
        'the strip': 'Las Vegas', 'fremont street': 'Las Vegas',
        'downtown las vegas': 'Las Vegas', 'paradise': 'Las Vegas', 'henderson': 'Las Vegas',
        // Austin
        'south congress': 'Austin', 'sixth street': 'Austin',
        'east austin': 'Austin', 'domain austin': 'Austin', 'barton hills': 'Austin',
        // Nashville
        'the gulch': 'Nashville', 'east nashville': 'Nashville', '12 south': 'Nashville',
        'germantown nashville': 'Nashville', 'hillsboro village': 'Nashville',
        'sylvan park': 'Nashville', 'downtown nashville': 'Nashville',
        // Atlanta
        'midtown atlanta': 'Atlanta', 'buckhead': 'Atlanta', 'virginia-highland': 'Atlanta',
        'little five points': 'Atlanta', 'inman park': 'Atlanta', 'cabbagetown': 'Atlanta',
        'grant park atlanta': 'Atlanta', 'east atlanta': 'Atlanta', 'west midtown atlanta': 'Atlanta',
        // Denver
        'lodo': 'Denver', 'capitol hill denver': 'Denver', 'rino': 'Denver',
        'cherry creek': 'Denver', 'washington park': 'Denver', 'highlands denver': 'Denver',
        'baker denver': 'Denver', 'five points denver': 'Denver',
        // Dallas
        'uptown dallas': 'Dallas', 'deep ellum': 'Dallas', 'bishop arts': 'Dallas',
        'design district dallas': 'Dallas', 'oak cliff': 'Dallas', 'downtown dallas': 'Dallas',
        // Houston
        'midtown houston': 'Houston', 'montrose': 'Houston', 'heights houston': 'Houston',
        'museum district houston': 'Houston', 'rice village': 'Houston',
        'river oaks': 'Houston', 'downtown houston': 'Houston', 'galleria houston': 'Houston',
        // San Diego
        'gaslamp quarter': 'San Diego', 'pacific beach': 'San Diego', 'ocean beach': 'San Diego',
        'north park': 'San Diego', 'hillcrest': 'San Diego', 'la jolla': 'San Diego',
        'mission hills': 'San Diego', 'little italy san diego': 'San Diego',
        'mission valley': 'San Diego', 'old town san diego': 'San Diego',
        // Portland
        'pearl district': 'Portland', 'alberta': 'Portland', 'mississippi portland': 'Portland',
        'hawthorne': 'Portland', 'division portland': 'Portland', 'nob hill portland': 'Portland',
        'southeast portland': 'Portland', 'north portland': 'Portland',
        // Minneapolis
        'uptown minneapolis': 'Minneapolis', 'warehouse district minneapolis': 'Minneapolis',
        'northeast minneapolis': 'Minneapolis', 'north loop': 'Minneapolis',
        // Phoenix / Scottsdale
        'old town scottsdale': 'Scottsdale', 'scottsdale old town': 'Scottsdale',
        'tempe': 'Phoenix', 'mesa': 'Phoenix', 'chandler': 'Phoenix',
        'downtown phoenix': 'Phoenix', 'midtown phoenix': 'Phoenix',
    },
    CA: {
        'gastown': 'Vancouver', 'yaletown': 'Vancouver', 'kitsilano': 'Vancouver',
        'west end': 'Vancouver', 'granville island': 'Vancouver',
        'mount pleasant vancouver': 'Vancouver', 'commercial drive': 'Vancouver',
        'strathcona': 'Vancouver', 'chinatown vancouver': 'Vancouver',
        'fairview vancouver': 'Vancouver', 'riley park': 'Vancouver',
        'yorkville': 'Toronto', 'distillery district': 'Toronto', 'king west': 'Toronto',
        'kensington market': 'Toronto', 'annex': 'Toronto', 'queen west': 'Toronto',
        'roncesvalles': 'Toronto', 'leslieville': 'Toronto', 'little italy toronto': 'Toronto',
        'greektown toronto': 'Toronto', 'the junction': 'Toronto', 'corktown': 'Toronto',
        'st lawrence': 'Toronto', 'harbourfront toronto': 'Toronto', 'entertainment district toronto': 'Toronto',
        'old montreal': 'Montreal', 'plateau': 'Montreal', 'mile end': 'Montreal',
        'griffintown': 'Montreal', 'rosemont': 'Montreal', 'villeray': 'Montreal',
        'hochelaga': 'Montreal', 'petite-patrie': 'Montreal', 'outremont': 'Montreal',
        'westmount': 'Montreal', 'ndg': 'Montreal', 'cote-des-neiges': 'Montreal',
        'old quebec': 'Quebec City', 'saint-roch': 'Quebec City',
        'downtown calgary': 'Calgary', 'beltline calgary': 'Calgary', 'inglewood calgary': 'Calgary',
        'kensington calgary': 'Calgary', 'mission calgary': 'Calgary',
        'whyte ave': 'Edmonton', 'old strathcona': 'Edmonton',
        'downtown ottawa': 'Ottawa', 'byward market': 'Ottawa', 'glebe': 'Ottawa',
        'downtown winnipeg': 'Winnipeg', 'exchange district': 'Winnipeg',
        'north end halifax': 'Halifax', 'south end halifax': 'Halifax',
    },
    MX: {
        'polanco': 'Mexico City', 'condesa': 'Mexico City', 'roma': 'Mexico City',
        'coyoacan': 'Mexico City', 'zona rosa': 'Mexico City', 'santa fe': 'Mexico City',
        'napoles': 'Mexico City', 'del valle': 'Mexico City', 'narvarte': 'Mexico City',
        'juarez cdmx': 'Mexico City', 'tepito': 'Mexico City', 'centro historico cdmx': 'Mexico City',
        'xochimilco': 'Mexico City', 'tlalpan': 'Mexico City', 'pedregal': 'Mexico City',
        'hotel zone': 'Cancun', 'zona hotelera': 'Cancun', 'downtown cancun': 'Cancun',
        'quinta avenida': 'Playa del Carmen', '5th avenue': 'Playa del Carmen',
        'centro playa': 'Playa del Carmen',
        'old guadalajara': 'Guadalajara', 'chapultepec guadalajara': 'Guadalajara',
        'tlaquepaque': 'Guadalajara', 'zona minerva': 'Guadalajara',
        'tecnologico': 'Monterrey', 'san pedro garza garcia': 'Monterrey', 'barrio antiguo': 'Monterrey',
        'tulum town': 'Tulum', 'la veleta': 'Tulum',
        'sayulita': 'Puerto Vallarta', 'old town pv': 'Puerto Vallarta', 'zona romantica': 'Puerto Vallarta',
    },
    // ── South America ──────────────────────────────────────────────────────────
    BR: {
        'copacabana': 'Rio de Janeiro', 'ipanema': 'Rio de Janeiro', 'leblon': 'Rio de Janeiro',
        'barra da tijuca': 'Rio de Janeiro', 'lapa': 'Rio de Janeiro',
        'santa teresa': 'Rio de Janeiro', 'botafogo': 'Rio de Janeiro', 'flamengo': 'Rio de Janeiro',
        'urca': 'Rio de Janeiro', 'gavea': 'Rio de Janeiro', 'jardim botanico': 'Rio de Janeiro',
        'glorio': 'Rio de Janeiro', 'centro rio': 'Rio de Janeiro', 'tijuca': 'Rio de Janeiro',
        'jardins': 'Sao Paulo', 'pinheiros': 'Sao Paulo', 'moema': 'Sao Paulo',
        'vila olimpia': 'Sao Paulo', 'itaim bibi': 'Sao Paulo', 'liberdade': 'Sao Paulo',
        'consolacao': 'Sao Paulo', 'higienopolis': 'Sao Paulo', 'brooklin': 'Sao Paulo',
        'perdizes': 'Sao Paulo', 'vila madalena': 'Sao Paulo', 'bela vista': 'Sao Paulo',
        'bom retiro': 'Sao Paulo', 'centro sp': 'Sao Paulo',
        'savassi': 'Belo Horizonte', 'funcionarios': 'Belo Horizonte',
        'pelourinho': 'Salvador', 'barra salvador': 'Salvador',
    },
    AR: {
        'palermo': 'Buenos Aires', 'recoleta': 'Buenos Aires', 'san telmo': 'Buenos Aires',
        'puerto madero': 'Buenos Aires', 'microcentro': 'Buenos Aires', 'belgrano': 'Buenos Aires',
        'villa crespo': 'Buenos Aires', 'caballito': 'Buenos Aires', 'flores': 'Buenos Aires',
        'colegiales': 'Buenos Aires', 'nunez': 'Buenos Aires', 'almagro': 'Buenos Aires',
        'boedo': 'Buenos Aires', 'la boca': 'Buenos Aires', 'villa del parque': 'Buenos Aires',
    },
    CL: {
        'las condes': 'Santiago', 'providencia': 'Santiago', 'vitacura': 'Santiago',
        'barrio italia': 'Santiago', 'bellavista': 'Santiago', 'nunooa': 'Santiago',
        'miraflores santiago': 'Santiago', 'centro santiago': 'Santiago', 'lastarria': 'Santiago',
        'cerro alegre': 'Valparaiso', 'cerro concepcion': 'Valparaiso',
    },
    CO: {
        'chapinero': 'Bogota', 'zona rosa bogota': 'Bogota', 'usaquen': 'Bogota',
        'la candelaria': 'Bogota', 'teusaquillo': 'Bogota', 'el poblado': 'Medellin',
        'laureles': 'Medellin', 'envigado': 'Medellin', 'bello': 'Medellin',
        'getsemani': 'Cartagena', 'centro historico cartagena': 'Cartagena',
        'bocagrande': 'Cartagena', 'manga': 'Cartagena',
    },
    PE: {
        'miraflores': 'Lima', 'barranco': 'Lima', 'san isidro': 'Lima', 'surco': 'Lima',
        'la molina': 'Lima', 'magdalena': 'Lima', 'pueblo libre': 'Lima',
        'lince': 'Lima', 'san borja': 'Lima', 'jesus maria': 'Lima',
        'central lima': 'Lima', 'callao': 'Lima',
    },
    EC: {
        'la mariscal': 'Quito', 'la carolina': 'Quito', 'cumbaya': 'Quito',
        'malecon simon bolivar': 'Guayaquil', 'las penas': 'Guayaquil',
    },
    UY: {
        'pocitos': 'Montevideo', 'ciudad vieja': 'Montevideo', 'punta carretas': 'Montevideo',
        'punta del este downtown': 'Punta del Este',
    },
    // ── Europe ─────────────────────────────────────────────────────────────────
    GB: {
        'westminster': 'London', 'soho': 'London', 'chelsea': 'London',
        'kensington': 'London', 'mayfair': 'London', 'camden': 'London',
        'shoreditch': 'London', 'canary wharf': 'London', 'greenwich': 'London',
        'notting hill': 'London', 'covent garden': 'London', 'brixton': 'London',
        'islington': 'London', 'hackney': 'London', 'bethnal green': 'London',
        'elephant and castle': 'London', 'south bank': 'London', 'city of london': 'London',
        'bermondsey': 'London', 'peckham': 'London', 'dulwich': 'London',
        'crystal palace': 'London', 'stratford': 'London', 'east london': 'London',
        'angel': 'London', 'clerkenwell': 'London', 'farringdon': 'London',
        'holborn': 'London', 'bloomsbury': 'London', 'fitzrovia': 'London',
        'marylebone': 'London', 'paddington': 'London', 'bayswater': 'London',
        'shepherd s bush': 'London', 'hammersmith': 'London', 'fulham': 'London',
        'putney': 'London', 'wimbledon': 'London', 'richmond': 'London',
        'twickenham': 'London', 'kingston': 'London', 'croydon': 'London',
        'northern quarter': 'Manchester', 'ancoats': 'Manchester', 'spinningfields': 'Manchester',
        'salford': 'Manchester', 'didsbury': 'Manchester', 'chorlton': 'Manchester',
        'castlefield': 'Manchester', 'deansgate': 'Manchester',
        'old town edinburgh': 'Edinburgh', 'new town edinburgh': 'Edinburgh',
        'leith': 'Edinburgh', 'stockbridge': 'Edinburgh', 'morningside': 'Edinburgh',
        'west end edinburgh': 'Edinburgh',
        'merchant city': 'Glasgow', 'west end glasgow': 'Glasgow', 'southside glasgow': 'Glasgow',
        'jewellery quarter': 'Birmingham', 'digbeth': 'Birmingham', 'edgbaston': 'Birmingham',
        'broad street birmingham': 'Birmingham',
        'harbourside': 'Bristol', 'clifton': 'Bristol', 'stokes croft': 'Bristol',
        'bedminster': 'Bristol',
        'headingley': 'Leeds', 'chapel allerton': 'Leeds', 'holbeck urban village': 'Leeds',
        'city centre sheffield': 'Sheffield', 'kelham island': 'Sheffield',
    },
    FR: {
        'montmartre': 'Paris', 'le marais': 'Paris', 'saint-germain': 'Paris',
        'latin quarter': 'Paris', 'bastille': 'Paris', 'pigalle': 'Paris',
        'champs elysees': 'Paris', 'opera': 'Paris', 'republique': 'Paris',
        'belleville': 'Paris', 'oberkampf': 'Paris', 'batignolles': 'Paris',
        'canal saint-martin': 'Paris', 'nation': 'Paris', 'vincennes': 'Paris',
        'boulogne-billancourt': 'Paris', 'neuilly': 'Paris', 'levallois': 'Paris',
        'saint-ouen': 'Paris', 'montreuil': 'Paris', 'pantin': 'Paris',
        'vieux port': 'Marseille', 'le panier': 'Marseille', 'castellane': 'Marseille',
        'joliette': 'Marseille', 'corniche marseille': 'Marseille',
        'presquile': 'Lyon', 'croix rousse': 'Lyon', 'vieux lyon': 'Lyon',
        'confluence': 'Lyon', 'part-dieu': 'Lyon',
        'vieux nice': 'Nice', 'promenade des anglais': 'Nice', 'cimiez': 'Nice',
        'cours mirabeau': 'Aix-en-Provence',
        'saint-pierre': 'Bordeaux', 'chartrons': 'Bordeaux', 'bacalan': 'Bordeaux',
        'grande ile': 'Strasbourg', 'krutenau': 'Strasbourg',
        'ile feydeau': 'Nantes', 'bouffay': 'Nantes',
        'saint-malo old town': 'Saint-Malo',
    },
    ES: {
        'gothic quarter': 'Barcelona', 'gotico': 'Barcelona', 'el born': 'Barcelona',
        'gracia': 'Barcelona', 'eixample': 'Barcelona', 'barceloneta': 'Barcelona',
        'poblenou': 'Barcelona', 'raval': 'Barcelona', 'montjuic': 'Barcelona',
        'sarria': 'Barcelona', 'les corts': 'Barcelona', 'gaudi': 'Barcelona',
        'sant andreu': 'Barcelona', 'clot': 'Barcelona', 'glories': 'Barcelona',
        'malasana': 'Madrid', 'chueca': 'Madrid', 'lavapies': 'Madrid',
        'retiro': 'Madrid', 'salamanca madrid': 'Madrid', 'sol': 'Madrid',
        'arganzuela': 'Madrid', 'chamberi': 'Madrid', 'usera': 'Madrid',
        'carabanchel': 'Madrid', 'vallecas': 'Madrid', 'leganes': 'Madrid',
        'santa cruz': 'Seville', 'triana': 'Seville', 'arenal': 'Seville',
        'nervion': 'Seville', 'alameda': 'Seville',
        'albaicin': 'Granada', 'realejo': 'Granada', 'sacromonte': 'Granada',
        'ruzafa': 'Valencia', 'el carmen': 'Valencia', 'cabanyal': 'Valencia',
        'benimaclet': 'Valencia', 'l eixample valencia': 'Valencia',
        'casco viejo bilbao': 'Bilbao', 'abando': 'Bilbao', 'deusto': 'Bilbao',
        'parte vieja': 'San Sebastian', 'gros': 'San Sebastian', 'centro donostia': 'San Sebastian',
        'old town malaga': 'Malaga', 'soho malaga': 'Malaga', 'teatinos': 'Malaga',
        'palma old town': 'Palma de Mallorca', 'santa catalina': 'Palma de Mallorca',
    },
    IT: {
        'trastevere': 'Rome', 'vatican': 'Rome', 'prati': 'Rome',
        'testaccio': 'Rome', 'pigneto': 'Rome', 'monti': 'Rome',
        'parioli': 'Rome', 'esquilino': 'Rome', 'ostiense': 'Rome',
        'garbatella': 'Rome', 'flaminio': 'Rome', 'pignola': 'Rome',
        'navigli': 'Milan', 'brera': 'Milan', 'porta nuova': 'Milan',
        'isola': 'Milan', 'porta venezia': 'Milan', 'magenta': 'Milan',
        'centro storico milan': 'Milan', 'duomo area': 'Milan', 'ticinese': 'Milan',
        'porta romana': 'Milan', 'città studi': 'Milan', 'loreto': 'Milan',
        'cannaregio': 'Venice', 'dorsoduro': 'Venice', 'san polo': 'Venice',
        'castello venice': 'Venice', 'giudecca': 'Venice', 'mestre': 'Venice',
        'lido di venezia': 'Venice',
        'oltrarno': 'Florence', 'santa croce': 'Florence', 'san giovanni': 'Florence',
        'san marco florence': 'Florence', 'santa maria novella': 'Florence',
        'spaccanapoli': 'Naples', 'chiaia': 'Naples', 'posillipo': 'Naples',
        'vomero': 'Naples', 'quartieri spagnoli': 'Naples', 'piazza garibaldi naples': 'Naples',
        'centro storico naples': 'Naples',
        'quadrilatero romano': 'Turin', 'san salvario': 'Turin', 'vanchiglia': 'Turin',
        'cit turin': 'Turin', 'aurora': 'Turin',
        'quadrilatero': 'Bologna', 'bolognina': 'Bologna', 'porto bologna': 'Bologna',
        'centro storico genoa': 'Genoa', 'boccadasse': 'Genoa',
        'catania city center': 'Catania', 'centro storico palermo': 'Palermo',
    },
    DE: {
        'mitte': 'Berlin', 'kreuzberg': 'Berlin', 'prenzlauer berg': 'Berlin',
        'friedrichshain': 'Berlin', 'charlottenburg': 'Berlin', 'schoneberg': 'Berlin',
        'neukölln': 'Berlin', 'steglitz': 'Berlin', 'tempelhof': 'Berlin',
        'spandau': 'Berlin', 'wedding': 'Berlin', 'reinickendorf': 'Berlin',
        'treptow': 'Berlin', 'pankow': 'Berlin', 'lichtenberg': 'Berlin',
        'marzahn': 'Berlin', 'tiergarten berlin': 'Berlin', 'wilmersdorf': 'Berlin',
        'schwabing': 'Munich', 'maxvorstadt': 'Munich', 'glockenbachviertel': 'Munich',
        'bogenhausen': 'Munich', 'haidhausen': 'Munich', 'giesing': 'Munich',
        'nymphenburg': 'Munich', 'neuhausen': 'Munich', 'lehel': 'Munich',
        'altstadt hamburg': 'Hamburg', 'hafencity': 'Hamburg', 'eppendorf': 'Hamburg',
        'altona': 'Hamburg', 'eimsbüttel': 'Hamburg', 'winterhude': 'Hamburg',
        'rotherbaum': 'Hamburg', 'st pauli': 'Hamburg', 'barmbek': 'Hamburg',
        'sachsenhausen': 'Frankfurt', 'bornheim': 'Frankfurt', 'nordend': 'Frankfurt',
        'westend frankfurt': 'Frankfurt', 'bockenheim': 'Frankfurt', 'bahnhofsviertel': 'Frankfurt',
        'innenstadt frankfurt': 'Frankfurt',
        'altstadt cologne': 'Cologne', 'ehrenfeld': 'Cologne', 'nippes': 'Cologne',
        'sülz': 'Cologne', 'lindenthal': 'Cologne',
        'altstadt düsseldorf': 'Dusseldorf', 'friedrichstadt duss': 'Dusseldorf',
        'gerresheim': 'Dusseldorf', 'pempelfort': 'Dusseldorf',
        'bohnenviertel': 'Stuttgart', 'west stuttgart': 'Stuttgart', 'bad cannstatt': 'Stuttgart',
        'sebald': 'Nuremberg', 'lorenz': 'Nuremberg', 'gostenhof': 'Nuremberg',
        'connewitz': 'Leipzig', 'gohlis': 'Leipzig', 'plagwitz': 'Leipzig',
        'neustadt dresden': 'Dresden', 'altstadt dresden': 'Dresden',
    },
    NL: {
        'jordaan': 'Amsterdam', 'de pijp': 'Amsterdam', 'centrum': 'Amsterdam',
        'oud west': 'Amsterdam', 'east amsterdam': 'Amsterdam', 'westerpark': 'Amsterdam',
        'oud-oost': 'Amsterdam', 'noord amsterdam': 'Amsterdam', 'nieuw-west': 'Amsterdam',
        'buitenveldert': 'Amsterdam', 'zuidas': 'Amsterdam', 'rivierenbuurt': 'Amsterdam',
        'centrum rotterdam': 'Rotterdam', 'kop van zuid': 'Rotterdam', 'katendrecht': 'Rotterdam',
        'witte de withstraat': 'Rotterdam',
        'centrum den haag': 'The Hague', 'scheveningen': 'The Hague', 'bezuidenhout': 'The Hague',
        'oudwijk': 'Utrecht', 'lombok': 'Utrecht',
    },
    PT: {
        'alfama': 'Lisbon', 'bairro alto': 'Lisbon', 'belem': 'Lisbon',
        'chiado': 'Lisbon', 'mouraria': 'Lisbon', 'intendente': 'Lisbon',
        'avenidas novas': 'Lisbon', 'campo de ourique': 'Lisbon', 'santos': 'Lisbon',
        'alcantara': 'Lisbon', 'bica': 'Lisbon', 'principe real': 'Lisbon',
        'graça': 'Lisbon', 'estrela': 'Lisbon', 'campolide': 'Lisbon',
        'ribeira': 'Porto', 'vila nova de gaia': 'Porto', 'boavista': 'Porto',
        'bonfim': 'Porto', 'cedofeita': 'Porto', 'miragaia': 'Porto',
        'foz do douro': 'Porto',
        'albufeira old town': 'Albufeira', 'oura': 'Albufeira', 'falesia': 'Albufeira',
        'vilamoura': 'Vilamoura', 'quarteira': 'Vilamoura',
        'praia da rocha': 'Portimao', 'alvor': 'Portimao',
        'lagos algarve': 'Lagos', 'meia praia': 'Lagos',
        'tavira old town': 'Tavira',
        'faro old town': 'Faro',
    },
    GR: {
        'plaka': 'Athens', 'monastiraki': 'Athens', 'kolonaki': 'Athens',
        'psiri': 'Athens', 'thissio': 'Athens', 'exarchia': 'Athens',
        'gazi': 'Athens', 'koukaki': 'Athens', 'petralona': 'Athens',
        'glyfada': 'Athens', 'vouliagmeni': 'Athens', 'piraeus': 'Athens',
        'oia': 'Santorini', 'fira': 'Santorini', 'imerovigli': 'Santorini',
        'akrotiri': 'Santorini', 'perivolos': 'Santorini',
        'mykonos town': 'Mykonos', 'little venice': 'Mykonos', 'ornos': 'Mykonos',
        'platys gialos': 'Mykonos', 'psarou': 'Mykonos',
        'old town rhodes': 'Rhodes', 'ixia': 'Rhodes', 'faliraki': 'Rhodes',
        'hersonissos': 'Heraklion', 'chania old town': 'Chania', 'elounda': 'Agios Nikolaos',
        'agios nikolaos crete': 'Agios Nikolaos',
        'corfu town': 'Corfu',
    },
    CZ: {
        'old town': 'Prague', 'mala strana': 'Prague', 'vinohrady': 'Prague',
        'zizkov': 'Prague', 'josefov': 'Prague', 'nove mesto': 'Prague',
        'holesovice': 'Prague', 'dejvice': 'Prague', 'smichov': 'Prague',
        'nusle': 'Prague', 'zbraslav': 'Prague',
    },
    PL: {
        'old town warsaw': 'Warsaw', 'praga': 'Warsaw', 'srodmiescie': 'Warsaw',
        'mokotow': 'Warsaw', 'ursynow': 'Warsaw', 'zoliborz': 'Warsaw',
        'wola': 'Warsaw', 'wlochy': 'Warsaw',
        'kazimierz': 'Krakow', 'stare miasto': 'Krakow', 'podgorze': 'Krakow',
        'krowodrza': 'Krakow', 'nowa huta': 'Krakow',
        'wrzeszcz': 'Gdansk', 'old town gdansk': 'Gdansk', 'oliwa': 'Gdansk',
        'jelitkow': 'Gdansk',
    },
    HU: {
        'buda': 'Budapest', 'pest': 'Budapest', 'castle district': 'Budapest',
        'jewish quarter': 'Budapest', 'erzsebetvaros': 'Budapest',
        'belvaros': 'Budapest', 'lipotvaros': 'Budapest', 'terezvaros': 'Budapest',
        'jozsefvaros': 'Budapest', 'ferencvaros': 'Budapest', 'ujpest': 'Budapest',
        'obuda': 'Budapest',
    },
    RU: {
        'arbat': 'Moscow', 'red square': 'Moscow', 'kitay gorod': 'Moscow',
        'tverskaya': 'Moscow', 'zamoskvorechye': 'Moscow', 'chistye prudy': 'Moscow',
        'patriarshy ponds': 'Moscow', 'khamovniki': 'Moscow',
        'nevsky prospekt': 'Saint Petersburg', 'vasilievsky island': 'Saint Petersburg',
        'petrogradsky': 'Saint Petersburg', 'vyborg side': 'Saint Petersburg',
        'sennaya': 'Saint Petersburg',
    },
    // ── Middle East ────────────────────────────────────────────────────────────
    AE: {
        'marina': 'Dubai', 'dubai marina': 'Dubai', 'jbr': 'Dubai',
        'deira': 'Dubai', 'bur dubai': 'Dubai', 'downtown dubai': 'Dubai',
        'jlt': 'Dubai', 'palm jumeirah': 'Dubai', 'difc': 'Dubai',
        'jumeirah': 'Dubai', 'business bay': 'Dubai', 'al quoz': 'Dubai',
        'creek': 'Dubai', 'festival city': 'Dubai', 'international city': 'Dubai',
        'al barsha': 'Dubai', 'motor city': 'Dubai', 'silicon oasis': 'Dubai',
        'mirdif': 'Dubai', 'rashidiya': 'Dubai', 'karama': 'Dubai',
        'satwa': 'Dubai', 'oud metha': 'Dubai', 'al nahda dubai': 'Dubai',
        'downtown abu dhabi': 'Abu Dhabi', 'corniche abu dhabi': 'Abu Dhabi',
        'al reem island': 'Abu Dhabi', 'yas island': 'Abu Dhabi', 'saadiyat island': 'Abu Dhabi',
        'al maryah island': 'Abu Dhabi', 'khalidiyah': 'Abu Dhabi',
        'sharjah city center': 'Sharjah',
    },
    TR: {
        'sultanahmet': 'Istanbul', 'taksim': 'Istanbul', 'beyoglu': 'Istanbul',
        'kadikoy': 'Istanbul', 'besiktas': 'Istanbul', 'eminonu': 'Istanbul',
        'galata': 'Istanbul', 'sisli': 'Istanbul', 'uskudar': 'Istanbul',
        'cihangir': 'Istanbul', 'balat': 'Istanbul', 'fatih': 'Istanbul',
        'bakirkoy': 'Istanbul', 'florya': 'Istanbul', 'levent': 'Istanbul',
        'etiler': 'Istanbul', 'bebek': 'Istanbul', 'ortakoy': 'Istanbul',
        'arnavutkoy': 'Istanbul', 'bosphorus': 'Istanbul',
        'kalkan': 'Kalkan', 'kas': 'Kas', 'fethiye center': 'Fethiye',
        'oludeniz': 'Fethiye', 'antalya old town': 'Antalya', 'konyaalti': 'Antalya',
        'lara beach': 'Antalya', 'bodrum peninsula': 'Bodrum', 'yalikavak': 'Bodrum',
        'turgutreis': 'Bodrum', 'bitez': 'Bodrum',
    },
    IL: {
        'jaffa': 'Tel Aviv', 'yafo': 'Tel Aviv', 'neve tzedek': 'Tel Aviv',
        'florentin': 'Tel Aviv', 'rothschild': 'Tel Aviv', 'dizengoff': 'Tel Aviv',
        'north tel aviv': 'Tel Aviv', 'ramat aviv': 'Tel Aviv', 'bat yam': 'Tel Aviv',
        'old city': 'Jerusalem', 'city center jerusalem': 'Jerusalem', 'nahlaot': 'Jerusalem',
        'german colony': 'Jerusalem', 'mamilla': 'Jerusalem',
    },
    QA: {
        'west bay': 'Doha', 'the pearl': 'Doha', 'lusail': 'Doha',
        'katara': 'Doha', 'msheireb': 'Doha', 'corniche doha': 'Doha',
        'old airport doha': 'Doha', 'al sadd': 'Doha', 'al waab': 'Doha',
    },
    SA: {
        'al olaya': 'Riyadh', 'malaz': 'Riyadh', 'diplomatic quarter': 'Riyadh',
        'king fahd road': 'Riyadh', 'exit 7': 'Riyadh', 'al wurud': 'Riyadh',
        'al balad': 'Jeddah', 'corniche jeddah': 'Jeddah', 'al hamra': 'Jeddah',
        'al rawdah': 'Jeddah', 'obhur': 'Jeddah',
        'madinah center': 'Medina',
    },
    JO: {
        'rainbow street': 'Amman', 'abdoun': 'Amman', 'shmeisani': 'Amman',
        'sweifieh': 'Amman', 'downtown amman': 'Amman', 'jabal amman': 'Amman',
        'wadi musa': 'Petra',
    },
    LB: {
        'hamra': 'Beirut', 'mar mikhael': 'Beirut', 'gemmayzeh': 'Beirut',
        'ashrafieh': 'Beirut', 'downtown beirut': 'Beirut', 'verdun': 'Beirut',
        'jnah': 'Beirut',
    },
    // ── Africa ─────────────────────────────────────────────────────────────────
    EG: {
        'zamalek': 'Cairo', 'maadi': 'Cairo', 'garden city': 'Cairo',
        'downtown cairo': 'Cairo', 'islamic cairo': 'Cairo',
        'giza': 'Cairo', 'dokki': 'Cairo', 'mohandessin': 'Cairo',
        'heliopolis': 'Cairo', 'nasr city': 'Cairo', 'rehab city': 'Cairo',
        'new cairo': 'Cairo', '5th settlement': 'Cairo',
        'stanley': 'Alexandria', 'miami alexandria': 'Alexandria', 'raml station': 'Alexandria',
        'el montaza': 'Alexandria', 'sidi bishr': 'Alexandria',
    },
    MA: {
        'medina': 'Marrakech', 'gueliz': 'Marrakech', 'hivernage': 'Marrakech',
        'palmeraie': 'Marrakech', 'mellah': 'Marrakech',
        'fez el bali': 'Fez', 'fes medina': 'Fez', 'fes el jdid': 'Fez',
        'ain diab': 'Casablanca', 'maarif': 'Casablanca', 'anfa': 'Casablanca',
        'ville nouvelle': 'Casablanca',
        'agadir beach': 'Agadir', 'talborjt': 'Agadir',
        'asilah old town': 'Asilah',
        'chefchaouen old town': 'Chefchaouen',
    },
    ZA: {
        'waterfront': 'Cape Town', 'v&a waterfront': 'Cape Town', 'bo-kaap': 'Cape Town',
        'sea point': 'Cape Town', 'camps bay': 'Cape Town', 'green point': 'Cape Town',
        'de waterkant': 'Cape Town', 'gardens': 'Cape Town', 'oranjezicht': 'Cape Town',
        'woodstock': 'Cape Town', 'observatory': 'Cape Town', 'mowbray': 'Cape Town',
        'rondebosch': 'Cape Town', 'claremont': 'Cape Town', 'constantia': 'Cape Town',
        'hout bay': 'Cape Town', 'simons town': 'Cape Town', 'muizenberg': 'Cape Town',
        'sandton': 'Johannesburg', 'rosebank': 'Johannesburg', 'melrose arch': 'Johannesburg',
        'maboneng': 'Johannesburg', 'braamfontein': 'Johannesburg', 'parktown': 'Johannesburg',
        'soweto': 'Johannesburg', 'fourways': 'Johannesburg',
        'durban beachfront': 'Durban', 'umhlanga': 'Durban', 'berea durban': 'Durban',
        'ballito': 'Durban',
    },
    KE: {
        'westlands': 'Nairobi', 'karen': 'Nairobi', 'kilimani': 'Nairobi',
        'lavington': 'Nairobi', 'gigiri': 'Nairobi', 'parklands': 'Nairobi',
        'langata': 'Nairobi', 'upperhill': 'Nairobi', 'cbd nairobi': 'Nairobi',
        'ngong road': 'Nairobi', 'kileleshwa': 'Nairobi',
        'diani': 'Mombasa', 'nyali': 'Mombasa', 'old town mombasa': 'Mombasa',
    },
    // ── Asia Pacific ───────────────────────────────────────────────────────────
    JP: {
        // Tokyo
        'shibuya': 'Tokyo', 'shinjuku': 'Tokyo', 'ginza': 'Tokyo',
        'akihabara': 'Tokyo', 'harajuku': 'Tokyo', 'roppongi': 'Tokyo',
        'asakusa': 'Tokyo', 'ueno': 'Tokyo', 'ikebukuro': 'Tokyo', 'odaiba': 'Tokyo',
        'shimokitazawa': 'Tokyo', 'nakameguro': 'Tokyo', 'ebisu': 'Tokyo',
        'daikanyama': 'Tokyo', 'jiyugaoka': 'Tokyo', 'meguro': 'Tokyo',
        'gotanda': 'Tokyo', 'osaki': 'Tokyo', 'shinagawa': 'Tokyo',
        'yurakucho': 'Tokyo', 'marunouchi': 'Tokyo', 'otemachi': 'Tokyo',
        'nihonbashi': 'Tokyo', 'kanda': 'Tokyo', 'ochanomizu': 'Tokyo',
        'tsukiji': 'Tokyo', 'toyosu': 'Tokyo', 'kiyosumi': 'Tokyo',
        'monzen-nakacho': 'Tokyo', 'koenji': 'Tokyo', 'kagurazama': 'Tokyo',
        'yanaka': 'Tokyo', 'nezu': 'Tokyo', 'nishi-ogikubo': 'Tokyo',
        'sangenjaya': 'Tokyo', 'jungumae': 'Tokyo', 'omotesando': 'Tokyo',
        'akasaka': 'Tokyo', 'toranomon': 'Tokyo', 'shimbashi': 'Tokyo',
        'ryogoku': 'Tokyo', 'asakusabashi': 'Tokyo', 'kuramae': 'Tokyo',
        // Osaka
        'namba': 'Osaka', 'dotonbori': 'Osaka', 'umeda': 'Osaka', 'shinsaibashi': 'Osaka',
        'shinsekai': 'Osaka', 'tennoji': 'Osaka', 'amerikamura': 'Osaka',
        'nakazakicho': 'Osaka', 'kyobashi': 'Osaka', 'fukushima osaka': 'Osaka',
        'namba parks': 'Osaka', 'tanimachi': 'Osaka', 'shin-osaka': 'Osaka',
        // Kyoto
        'gion': 'Kyoto', 'arashiyama': 'Kyoto', 'fushimi': 'Kyoto',
        'nishiki': 'Kyoto', 'higashiyama': 'Kyoto', 'kawaramachi': 'Kyoto',
        'pontocho': 'Kyoto', 'kinkakuji': 'Kyoto', 'fushimi inari': 'Kyoto',
        'nijo': 'Kyoto', 'kitano': 'Kyoto',
        // Sapporo
        'susukino': 'Sapporo', 'odori sapporo': 'Sapporo', 'tanukikoji': 'Sapporo',
        // Fukuoka
        'tenjin': 'Fukuoka', 'nakasu': 'Fukuoka', 'hakata': 'Fukuoka',
        'daimyo': 'Fukuoka', 'yakuin': 'Fukuoka', 'ohori': 'Fukuoka',
        // Nagoya
        'sakae': 'Nagoya', 'nagoya station area': 'Nagoya', 'osu': 'Nagoya',
        'meiekis': 'Nagoya', 'chikusa': 'Nagoya',
        // Hiroshima
        'peace memorial': 'Hiroshima', 'hiroshima city center': 'Hiroshima',
        // Nara
        'nara park': 'Nara',
    },
    KR: {
        // Seoul
        'gangnam': 'Seoul', 'hongdae': 'Seoul', 'myeongdong': 'Seoul',
        'itaewon': 'Seoul', 'insadong': 'Seoul', 'bukchon': 'Seoul',
        'sinchon': 'Seoul', 'dongdaemun': 'Seoul', 'mapo': 'Seoul',
        'jongno': 'Seoul', 'namsan': 'Seoul', 'apgujeong': 'Seoul',
        'cheongdam': 'Seoul', 'hannam': 'Seoul', 'yeouido': 'Seoul',
        'hapjeong': 'Seoul', 'mangwon': 'Seoul', 'seongsu': 'Seoul',
        'euljiro': 'Seoul', 'gwanghwamun': 'Seoul', 'samcheong': 'Seoul',
        'seochon': 'Seoul', 'anguk': 'Seoul', 'noryangjin': 'Seoul',
        'yeongdeungpo': 'Seoul', 'gangdong': 'Seoul', 'songpa': 'Seoul',
        'jamsil': 'Seoul', 'nowon': 'Seoul', 'dobong': 'Seoul',
        'eunpyeong': 'Seoul', 'guro': 'Seoul', 'geumcheon': 'Seoul',
        'sillim': 'Seoul', 'gwanak': 'Seoul', 'dongjak': 'Seoul',
        'wangsimni': 'Seoul', 'majang': 'Seoul', 'yongsan': 'Seoul',
        // Busan
        'seomyeon': 'Busan', 'haeundae': 'Busan', 'gwangalli': 'Busan',
        'nampodong': 'Busan', 'jagalchi': 'Busan', 'busan station area': 'Busan',
        'oncheonjang': 'Busan', 'centum city': 'Busan', 'marine city': 'Busan',
        // Jeju
        'jeju city center': 'Jeju', 'seogwipo': 'Jeju', 'hallasan': 'Jeju',
    },
    CN: {
        'pudong': 'Shanghai', 'the bund': 'Shanghai', 'bund': 'Shanghai',
        'lujiazui': 'Shanghai', 'xintiandi': 'Shanghai', 'french concession': 'Shanghai',
        "jing'an": 'Shanghai', 'xuhui': 'Shanghai', 'changning': 'Shanghai',
        'putuo': 'Shanghai', 'hongqiao': 'Shanghai', 'minhang': 'Shanghai',
        'jiading': 'Shanghai',
        'sanlitun': 'Beijing', 'wangfujing': 'Beijing', 'hutong': 'Beijing',
        'nanluoguxiang': 'Beijing', 'dashilan': 'Beijing', 'chaoyang': 'Beijing',
        'dongcheng': 'Beijing', 'xicheng': 'Beijing', 'haidian': 'Beijing',
        'shunyi': 'Beijing', 'guomao': 'Beijing', 'cbd beijing': 'Beijing',
        'houhai': 'Beijing', 'gulou': 'Beijing', 'wudaokou': 'Beijing',
        'chunxi road': 'Chengdu', 'kuanzhai alley': 'Chengdu', 'jinli': 'Chengdu',
        'tianfu': 'Chengdu', 'wuhou': 'Chengdu', 'qingyang': 'Chengdu',
        'tianhe': 'Guangzhou', 'haizhu': 'Guangzhou', 'liwan': 'Guangzhou',
        'yuexiu': 'Guangzhou', 'zhujiang new town': 'Guangzhou',
        'futian': 'Shenzhen', 'nanshan': 'Shenzhen', 'luohu': 'Shenzhen',
        'bao an': 'Shenzhen', 'longhua': 'Shenzhen',
        'gulangyu': 'Xiamen', 'siming': 'Xiamen',
        'zhongshan road': 'Nanjing', 'xuanwu': 'Nanjing',
        'binjiang': 'Hangzhou', 'xihu': 'Hangzhou', 'west lake': 'Hangzhou',
    },
    HK: {
        'kowloon': 'Hong Kong', 'tsim sha tsui': 'Hong Kong', 'mong kok': 'Hong Kong',
        'wan chai': 'Hong Kong', 'causeway bay': 'Hong Kong', 'central': 'Hong Kong',
        'sheung wan': 'Hong Kong', 'admiralty': 'Hong Kong', 'kennedy town': 'Hong Kong',
        'jordan': 'Hong Kong', 'yau ma tei': 'Hong Kong', 'sham shui po': 'Hong Kong',
        'tai po': 'Hong Kong', 'sha tin': 'Hong Kong', 'tuen mun': 'Hong Kong',
        'north point': 'Hong Kong', 'quarry bay': 'Hong Kong', 'tai koo': 'Hong Kong',
        'happy valley': 'Hong Kong', 'wong chuk hang': 'Hong Kong',
        'aberdeen': 'Hong Kong', 'ap lei chau': 'Hong Kong',
        'stanley': 'Hong Kong', 'repulse bay': 'Hong Kong', 'shek o': 'Hong Kong',
    },
    TW: {
        'ximending': 'Taipei', 'daan': 'Taipei', 'zhongzheng': 'Taipei',
        'xinyi': 'Taipei', 'zhongshan': 'Taipei', 'datong': 'Taipei',
        'songshan': 'Taipei', 'neihu': 'Taipei', 'wenshan': 'Taipei',
        'shilin': 'Taipei', 'beitou': 'Taipei', 'wanhua': 'Taipei',
    },
    SG: {
        'orchard': 'Singapore', 'marina bay': 'Singapore', 'sentosa': 'Singapore',
        'clarke quay': 'Singapore', 'chinatown': 'Singapore', 'little india': 'Singapore',
        'kampong glam': 'Singapore', 'bugis': 'Singapore', 'tanjong pagar': 'Singapore',
        'boat quay': 'Singapore', 'robertson quay': 'Singapore',
        'novena': 'Singapore', 'tiong bahru': 'Singapore', 'lavender': 'Singapore',
        'geylang': 'Singapore', 'katong': 'Singapore', 'joo chiat': 'Singapore',
        'bedok': 'Singapore', 'tampines': 'Singapore', 'pasir ris': 'Singapore',
        'woodlands': 'Singapore', 'jurong': 'Singapore', 'clementi': 'Singapore',
        'buona vista': 'Singapore', 'one-north': 'Singapore', 'harbourfront': 'Singapore',
    },
    MY: {
        'klcc': 'Kuala Lumpur', 'bukit bintang': 'Kuala Lumpur', 'bangsar': 'Kuala Lumpur',
        'chow kit': 'Kuala Lumpur', 'chinatown kl': 'Kuala Lumpur', 'mont kiara': 'Kuala Lumpur',
        'hartamas': 'Kuala Lumpur', 'damansara': 'Kuala Lumpur', 'petaling jaya': 'Kuala Lumpur',
        'subang jaya': 'Kuala Lumpur', 'sunway': 'Kuala Lumpur', 'puchong': 'Kuala Lumpur',
        'cheras kl': 'Kuala Lumpur', 'ampang': 'Kuala Lumpur', 'wangsa maju': 'Kuala Lumpur',
        'kepong': 'Kuala Lumpur', 'sentul': 'Kuala Lumpur',
        'george town': 'Penang', 'batu ferringhi': 'Penang', 'gurney drive': 'Penang',
        'georgetown penang': 'Penang', 'air itam': 'Penang', 'jelutong': 'Penang',
        'johor bahru': 'Johor Bahru', 'jb city': 'Johor Bahru', 'iskandar': 'Johor Bahru',
        'kota kinabalu waterfront': 'Kota Kinabalu', 'likas': 'Kota Kinabalu',
        'kuching waterfront': 'Kuching',
    },
    TH: {
        'sukhumvit': 'Bangkok', 'silom': 'Bangkok', 'siam': 'Bangkok',
        'pratunam': 'Bangkok', 'khao san': 'Bangkok', 'sathorn': 'Bangkok',
        'ari': 'Bangkok', 'thonglor': 'Bangkok', 'ekkamai': 'Bangkok',
        'rattanakosin': 'Bangkok', 'old city bangkok': 'Bangkok',
        'asok': 'Bangkok', 'nana': 'Bangkok', 'phrom phong': 'Bangkok',
        'phaya thai': 'Bangkok', 'victory monument': 'Bangkok', 'mo chit': 'Bangkok',
        'chatuchak': 'Bangkok', 'lad phrao': 'Bangkok', 'on nut': 'Bangkok',
        'bearing': 'Bangkok', 'udomsuk': 'Bangkok', 'bang na': 'Bangkok',
        'riverside bangkok': 'Bangkok', 'yaowarat': 'Bangkok', 'chinatown bangkok': 'Bangkok',
        'nimman': 'Chiang Mai', 'nimmanhaemin': 'Chiang Mai', 'old city chiang mai': 'Chiang Mai',
        'santitham': 'Chiang Mai', 'chang klan': 'Chiang Mai', 'night bazaar': 'Chiang Mai',
        'ping river': 'Chiang Mai',
        'patong': 'Phuket', 'kata': 'Phuket', 'karon': 'Phuket',
        'bang tao': 'Phuket', 'kamala': 'Phuket', 'surin phuket': 'Phuket',
        'rawai': 'Phuket', 'chalong': 'Phuket', 'old town phuket': 'Phuket',
        'laguna phuket': 'Phuket', 'mai khao': 'Phuket', 'nai harn': 'Phuket',
        'jomtien': 'Pattaya', 'naklua': 'Pattaya', 'north pattaya': 'Pattaya',
        'south pattaya': 'Pattaya', 'pratumnak': 'Pattaya',
        'hua hin city': 'Hua Hin', 'cha-am': 'Hua Hin',
        'chaweng': 'Koh Samui', 'lamai': 'Koh Samui', 'bophut': 'Koh Samui',
        'maenam': 'Koh Samui', 'choengmon': 'Koh Samui',
        'haad rin': 'Koh Phangan', 'thong sala': 'Koh Phangan',
    },
    VN: {
        'district 1': 'Ho Chi Minh City', 'ben thanh': 'Ho Chi Minh City',
        'bui vien': 'Ho Chi Minh City', 'thao dien': 'Ho Chi Minh City',
        'phu my hung': 'Ho Chi Minh City', 'district 3': 'Ho Chi Minh City',
        'district 7': 'Ho Chi Minh City', 'binh thanh': 'Ho Chi Minh City',
        'tan binh': 'Ho Chi Minh City', 'go vap': 'Ho Chi Minh City',
        'old quarter': 'Hanoi', 'hoan kiem': 'Hanoi', 'tay ho': 'Hanoi',
        'ba dinh': 'Hanoi', 'dong da': 'Hanoi', 'cau giay': 'Hanoi',
        'long bien': 'Hanoi', 'hai ba trung': 'Hanoi',
        'hoi an old town': 'Hoi An', 'an bang beach': 'Hoi An', 'cam an': 'Hoi An',
        'da nang beach': 'Da Nang', 'my khe': 'Da Nang', 'non nuoc': 'Da Nang',
        'hue citadel': 'Hue',
        'nha trang beach': 'Nha Trang', 'tran phu': 'Nha Trang',
        'phu quoc center': 'Phu Quoc', 'long beach pq': 'Phu Quoc',
    },
    ID: {
        // Bali
        'seminyak': 'Bali', 'kuta': 'Bali', 'ubud': 'Bali', 'canggu': 'Bali',
        'nusa dua': 'Bali', 'legian': 'Bali', 'jimbaran': 'Bali', 'sanur': 'Bali',
        'uluwatu': 'Bali', 'petitenget': 'Bali', 'denpasar': 'Bali',
        'berawa': 'Bali', 'pererenan': 'Bali', 'echo beach': 'Bali',
        'kedewatan': 'Bali', 'tegalalang': 'Bali', 'kerobokan': 'Bali',
        'tanjung benoa': 'Bali', 'renon': 'Bali',
        // Jakarta
        'kemang': 'Jakarta', 'scbd': 'Jakarta', 'sudirman': 'Jakarta',
        'menteng': 'Jakarta', 'kebayoran baru': 'Jakarta', 'tebet': 'Jakarta',
        'mampang': 'Jakarta', 'pancoran': 'Jakarta', 'grogol': 'Jakarta',
        'kebon jeruk': 'Jakarta', 'pluit': 'Jakarta', 'kota tua': 'Jakarta',
        'ancol': 'Jakarta', 'kelapa gading': 'Jakarta', 'puri': 'Jakarta',
        'bintaro': 'Jakarta', 'cipete': 'Jakarta', 'cilandak': 'Jakarta',
        // Yogyakarta
        'malioboro': 'Yogyakarta', 'prawirotaman': 'Yogyakarta', 'kraton': 'Yogyakarta',
        'kotagede': 'Yogyakarta',
        // Lombok
        'senggigi': 'Lombok', 'kuta lombok': 'Lombok', 'gili trawangan': 'Lombok',
        'gili meno': 'Lombok', 'gili air': 'Lombok', 'mataram': 'Lombok',
        // Surabaya
        'gubeng': 'Surabaya', 'rungkut': 'Surabaya',
        // Medan
        'polonia': 'Medan',
        // Komodo
        'labuan bajo': 'Labuan Bajo',
    },
    IN: {
        // Mumbai
        'bandra': 'Mumbai', 'juhu': 'Mumbai', 'andheri': 'Mumbai', 'colaba': 'Mumbai',
        'lower parel': 'Mumbai', 'bkc': 'Mumbai', 'powai': 'Mumbai',
        'worli': 'Mumbai', 'prabhadevi': 'Mumbai', 'dadar': 'Mumbai',
        'chembur': 'Mumbai', 'malad': 'Mumbai', 'kandivali': 'Mumbai',
        'borivali': 'Mumbai', 'thane': 'Mumbai', 'navi mumbai': 'Mumbai',
        'fort mumbai': 'Mumbai', 'churchgate': 'Mumbai', 'marine lines': 'Mumbai',
        'versova': 'Mumbai', 'goregaon': 'Mumbai',
        // Delhi
        'connaught place': 'New Delhi', 'karol bagh': 'New Delhi', 'paharganj': 'New Delhi',
        'south delhi': 'New Delhi', 'hauz khas': 'New Delhi', 'lajpat nagar': 'New Delhi',
        'greater kailash': 'New Delhi', 'saket': 'New Delhi', 'vasant kunj': 'New Delhi',
        'gurgaon': 'New Delhi', 'gurugram': 'New Delhi', 'noida': 'New Delhi',
        'janakpuri': 'New Delhi', 'pitampura': 'New Delhi', 'rohini': 'New Delhi',
        'dwarka': 'New Delhi', 'rajouri garden': 'New Delhi', 'preet vihar': 'New Delhi',
        'laxmi nagar': 'New Delhi', 'nehru place': 'New Delhi', 'old delhi': 'New Delhi',
        // Bangalore
        'koramangala': 'Bangalore', 'indiranagar': 'Bangalore', 'whitefield': 'Bangalore',
        'jp nagar': 'Bangalore', 'hsr layout': 'Bangalore', 'btm layout': 'Bangalore',
        'jayanagar': 'Bangalore', 'malleswaram': 'Bangalore', 'hebbal': 'Bangalore',
        'yelahanka': 'Bangalore', 'marathahalli': 'Bangalore', 'electronic city': 'Bangalore',
        'sarjapur': 'Bangalore', 'bellandur': 'Bangalore', 'mg road': 'Bangalore',
        'brigade road': 'Bangalore', 'commercial street': 'Bangalore',
        // Chennai
        'anna nagar': 'Chennai', 't nagar': 'Chennai', 'mylapore': 'Chennai',
        'nungambakkam': 'Chennai', 'adyar': 'Chennai', 'velachery': 'Chennai',
        'guindy': 'Chennai', 'perambur': 'Chennai', 'egmore': 'Chennai',
        'chetpet': 'Chennai', 'kodambakkam': 'Chennai', 'teynampet': 'Chennai',
        // Hyderabad
        'banjara hills': 'Hyderabad', 'jubilee hills': 'Hyderabad', 'gachibowli': 'Hyderabad',
        'kondapur': 'Hyderabad', 'madhapur': 'Hyderabad', 'hitech city': 'Hyderabad',
        'ameerpet': 'Hyderabad', 'begumpet': 'Hyderabad', 'secunderabad': 'Hyderabad',
        'kukatpally': 'Hyderabad', 'lb nagar': 'Hyderabad', 'dilsukhnagar': 'Hyderabad',
        // Pune
        'koregaon park': 'Pune', 'kalyani nagar': 'Pune', 'baner': 'Pune',
        'viman nagar': 'Pune', 'hadapsar': 'Pune', 'kothrud': 'Pune',
        'shivajinagar': 'Pune', 'aundh': 'Pune', 'wakad': 'Pune',
        'pimple saudagar': 'Pune', 'hinjewadi': 'Pune', 'kharadi': 'Pune',
        // Goa
        'calangute': 'Goa', 'baga': 'Goa', 'anjuna': 'Goa', 'vagator': 'Goa',
        'palolem': 'Goa', 'arambol': 'Goa', 'candolim': 'Goa', 'sinquerim': 'Goa',
        'colva': 'Goa', 'benaulim': 'Goa', 'panaji': 'Goa', 'mapusa': 'Goa',
        'morjim': 'Goa', 'chapora': 'Goa', 'agonda': 'Goa', 'patnem': 'Goa',
        // Jaipur
        'bani park': 'Jaipur', 'civil lines jaipur': 'Jaipur', 'malviya nagar jaipur': 'Jaipur',
        'sindhi camp': 'Jaipur', 'old city jaipur': 'Jaipur',
        // Kolkata
        'park street': 'Kolkata', 'salt lake': 'Kolkata', 'new town kolkata': 'Kolkata',
        'ballygunge': 'Kolkata', 'behala': 'Kolkata', 'howrah': 'Kolkata',
        'lake town': 'Kolkata',
        // Ahmedabad
        'satellite': 'Ahmedabad', 'navrangpura': 'Ahmedabad', 'cg road': 'Ahmedabad',
        'prahladnagar': 'Ahmedabad',
        // Kerala
        'varkala': 'Thiruvananthapuram', 'kovalam': 'Thiruvananthapuram',
        'fort kochi': 'Kochi', 'marine drive kochi': 'Kochi',
        'alleppey': 'Alappuzha',
        // Agra / Varanasi
        'taj ganj': 'Agra',
        'assi ghat': 'Varanasi', 'dashashwamedh': 'Varanasi',
    },
    AU: {
        // Sydney
        'bondi': 'Sydney', 'bondi beach': 'Sydney', 'darling harbour': 'Sydney',
        'manly': 'Sydney', 'surry hills': 'Sydney', 'newtown': 'Sydney',
        'glebe': 'Sydney', 'potts point': 'Sydney', 'paddington': 'Sydney',
        'redfern': 'Sydney', 'chippendale': 'Sydney', 'pyrmont': 'Sydney',
        'balmain': 'Sydney', 'rozelle': 'Sydney', 'leichhardt': 'Sydney',
        'annandale': 'Sydney', 'ultimo': 'Sydney', 'darlinghurst': 'Sydney',
        'kings cross': 'Sydney', 'woolloomooloo': 'Sydney',
        'marrickville': 'Sydney', 'stanmore': 'Sydney', 'enmore': 'Sydney',
        'erskineville': 'Sydney', 'coogee': 'Sydney', 'bronte': 'Sydney',
        'randwick': 'Sydney', 'maroubra': 'Sydney', 'clovelly': 'Sydney',
        'neutral bay': 'Sydney', 'mosman': 'Sydney', 'north sydney': 'Sydney',
        'chatswood': 'Sydney', 'parramatta': 'Sydney', 'ryde': 'Sydney',
        'cronulla': 'Sydney', 'sutherland': 'Sydney',
        // Melbourne
        'st kilda': 'Melbourne', 'fitzroy': 'Melbourne', 'southbank': 'Melbourne',
        'collingwood': 'Melbourne', 'brunswick': 'Melbourne', 'richmond': 'Melbourne',
        'south yarra': 'Melbourne', 'toorak': 'Melbourne', 'armadale': 'Melbourne',
        'prahran': 'Melbourne', 'windsor': 'Melbourne', 'balaclava': 'Melbourne',
        'elwood': 'Melbourne', 'middle park': 'Melbourne', 'albert park': 'Melbourne',
        'port melbourne': 'Melbourne', 'docklands': 'Melbourne', 'carlton': 'Melbourne',
        'north melbourne': 'Melbourne', 'footscray': 'Melbourne', 'hawthorn': 'Melbourne',
        'malvern': 'Melbourne', 'glen iris': 'Melbourne', 'camberwell': 'Melbourne',
        'northcote': 'Melbourne', 'thornbury': 'Melbourne', 'preston': 'Melbourne',
        'box hill': 'Melbourne', 'glen waverley': 'Melbourne', 'caulfield': 'Melbourne',
        // Brisbane
        'fortitude valley': 'Brisbane', 'new farm': 'Brisbane',
        'west end brisbane': 'Brisbane', 'south brisbane': 'Brisbane',
        'spring hill': 'Brisbane', 'paddington brisbane': 'Brisbane',
        'cbd brisbane': 'Brisbane',
        // Perth
        'fremantle': 'Perth', 'northbridge': 'Perth', 'subiaco': 'Perth',
        'cottesloe': 'Perth', 'scarborough': 'Perth', 'leederville': 'Perth',
        'mount lawley': 'Perth', 'victoria park': 'Perth',
        // Adelaide
        'cbd adelaide': 'Adelaide', 'glenelg': 'Adelaide', 'norwood': 'Adelaide',
        'unley': 'Adelaide', 'prospect': 'Adelaide',
        // Gold Coast
        'surfers paradise': 'Gold Coast', 'broadbeach': 'Gold Coast',
        'burleigh heads': 'Gold Coast', 'coolangatta': 'Gold Coast',
        'main beach': 'Gold Coast',
        // Cairns / Tropical North
        'cairns esplanade': 'Cairns', 'palm cove': 'Cairns', 'port douglas': 'Cairns',
        // Other
        'manuka': 'Canberra', 'kingston canberra': 'Canberra',
        'darwin waterfront': 'Darwin',
        'hobart salamanca': 'Hobart',
    },
    NZ: {
        'ponsonby': 'Auckland', 'parnell': 'Auckland', 'newmarket': 'Auckland',
        'devonport': 'Auckland', 'mt eden': 'Auckland', 'grey lynn': 'Auckland',
        'newtown wellington': 'Wellington', 'cuba street': 'Wellington', 'te aro': 'Wellington',
        'thorndon': 'Wellington', 'karori': 'Wellington',
        'riccarton': 'Christchurch', 'merivale': 'Christchurch', 'central city christchurch': 'Christchurch',
        'queenstown bay': 'Queenstown', 'frankton': 'Queenstown', 'arrowtown': 'Queenstown',
        'wanaka township': 'Wanaka',
        'rotorua city': 'Rotorua',
    },
    // ── Philippines ────────────────────────────────────────────────────────────
    PH: {
        // Metro Manila — core districts
        'makati': 'Manila', 'bgc': 'Manila', 'bonifacio global city': 'Manila',
        'intramuros': 'Manila', 'binondo': 'Manila', 'malate': 'Manila',
        'ermita': 'Manila', 'paco': 'Manila', 'pandacan': 'Manila',
        'sampaloc': 'Manila', 'santa ana': 'Manila', 'santa cruz': 'Manila',
        'tondo': 'Manila', 'port area': 'Manila', 'san miguel manila': 'Manila',
        // Taguig / BGC
        'taguig': 'Manila', 'fort bonifacio': 'Manila', 'western bicutan': 'Manila',
        // Pasay / Entertainment City
        'pasay': 'Manila', 'entertainment city': 'Manila', 'mall of asia': 'Manila',
        'moa area': 'Manila', 'bay area manila': 'Manila',
        // Mandaluyong / Ortigas
        'mandaluyong': 'Manila', 'ortigas': 'Manila', 'ortigas center': 'Manila',
        'shaw': 'Manila', 'wack-wack': 'Manila',
        // Pasig / Eastwood
        'pasig': 'Manila', 'eastwood': 'Manila', 'kapitolyo': 'Manila',
        'ugong': 'Manila', 'bagong ilog': 'Manila',
        // Quezon City
        'quezon city': 'Manila', 'cubao': 'Manila', 'diliman': 'Manila',
        'fairview': 'Manila', 'novaliches': 'Manila', 'commonwealth': 'Manila',
        'philcoa': 'Manila', 'kamuning': 'Manila', 'araneta': 'Manila',
        'timog': 'Manila', 'scout area': 'Manila', 'west triangle': 'Manila',
        'katipunan': 'Manila', 'up diliman': 'Manila',
        // Marikina / San Juan
        'marikina': 'Manila', 'san juan': 'Manila', 'greenhills': 'Manila',
        // Parañaque / Las Piñas / Muntinlupa
        'paranaque': 'Manila', 'las pinas': 'Manila', 'muntinlupa': 'Manila',
        'alabang': 'Manila', 'bf homes': 'Manila', 'sucat': 'Manila',
        // Caloocan / Malabon / Navotas / Valenzuela
        'caloocan': 'Manila', 'malabon': 'Manila', 'navotas': 'Manila', 'valenzuela': 'Manila',
        // Antipolo (Rizal)
        'antipolo': 'Manila',
        // Cebu
        'it park': 'Cebu City', 'cebu it park': 'Cebu City', 'lahug': 'Cebu City',
        'ayala cebu': 'Cebu City', 'cebu business park': 'Cebu City',
        'colon cebu': 'Cebu City', 'carbon cebu': 'Cebu City',
        'mactan': 'Cebu City', 'lapu-lapu': 'Cebu City', 'lapu lapu': 'Cebu City',
        'mandaue': 'Cebu City', 'sm seaside': 'Cebu City',
        // Davao
        'lanang': 'Davao City', 'downtown davao': 'Davao City',
        'toril': 'Davao City', 'buhangin': 'Davao City', 'matina': 'Davao City',
        'ecoland': 'Davao City', 'agdao': 'Davao City', 'talomo': 'Davao City',
        // Boracay
        'station 1': 'Boracay', 'station 2': 'Boracay', 'station 3': 'Boracay',
        'd mall': 'Boracay', 'diniwid': 'Boracay', 'bulabog': 'Boracay',
        'white beach boracay': 'Boracay', 'puka beach': 'Boracay',
        // Palawan
        'el nido': 'El Nido', 'nacpan': 'El Nido', 'corong corong': 'El Nido',
        'coron': 'Coron', 'coron town': 'Coron', 'busuanga': 'Coron',
        'underground river': 'Puerto Princesa', 'sabang palawan': 'Puerto Princesa',
        // Bohol
        'panglao': 'Tagbilaran', 'alona beach': 'Tagbilaran', 'chocolate hills': 'Tagbilaran',
        'loboc': 'Tagbilaran',
        // Siargao
        'cloud 9': 'Siargao', 'general luna siargao': 'Siargao',
        'union siargao': 'Siargao', 'pacifico': 'Siargao',
        // Iloilo
        'smallville': 'Iloilo City', 'esplanade iloilo': 'Iloilo City',
        'festive walk': 'Iloilo City',
        // Bacolod
        'lacson': 'Bacolod', 'libertad bacolod': 'Bacolod',
        // Cagayan de Oro
        'limketkai': 'Cagayan de Oro',
        // Tagaytay / Baguio
        'tagaytay ridge': 'Tagaytay', 'taal vista': 'Tagaytay',
        'session road': 'Baguio', 'burnham park': 'Baguio', 'camp john hay': 'Baguio',
        // Zamboanga
        'fort pilar': 'Zamboanga City',
        // Batangas / Cavite
        'anilao': 'Batangas', 'nasugbu': 'Batangas',
    },
    // ── South / Southeast Asia additions ──────────────────────────────────────
    BD: {
        'gulshan': 'Dhaka', 'banani': 'Dhaka', 'dhanmondi': 'Dhaka',
        'uttara': 'Dhaka', 'motijheel': 'Dhaka', 'mirpur': 'Dhaka',
        'bashundhara': 'Dhaka', 'mohammadpur': 'Dhaka', 'rayer bazar': 'Dhaka',
        'agrabad': 'Chittagong', 'nasirabad': 'Chittagong',
    },
    LK: {
        'fort colombo': 'Colombo', 'pettah': 'Colombo', 'kollupitiya': 'Colombo',
        'bambalapitiya': 'Colombo', 'wellawatte': 'Colombo', 'mount lavinia': 'Colombo',
        'borella': 'Colombo', 'rajagiriya': 'Colombo', 'nugegoda': 'Colombo',
        'kandy city': 'Kandy', 'dalada maligawa': 'Kandy',
        'galle fort': 'Galle', 'unawatuna': 'Galle', 'mirissa': 'Galle',
        'hikkaduwa': 'Galle', 'weligama': 'Galle',
        'negombo beach': 'Negombo',
        'trincomalee beach': 'Trincomalee',
    },
    PK: {
        'gulberg': 'Lahore', 'dha lahore': 'Lahore', 'old city lahore': 'Lahore',
        'model town lahore': 'Lahore', 'johar town': 'Lahore',
        'clifton': 'Karachi', 'defence karachi': 'Karachi', 'saddar': 'Karachi',
        'gulshan-e-iqbal': 'Karachi', 'north nazimabad': 'Karachi', 'korangi': 'Karachi',
        'blue area': 'Islamabad', 'f-6': 'Islamabad', 'f-7': 'Islamabad',
        'f-8': 'Islamabad', 'f-10': 'Islamabad', 'g-9': 'Islamabad',
        'dha islamabad': 'Islamabad', 'bahria town islamabad': 'Islamabad',
    },
    MM: {
        'downtown yangon': 'Yangon', 'chinatown yangon': 'Yangon', 'dagon': 'Yangon',
        'insein': 'Yangon', 'hledan': 'Yangon', 'tamwe': 'Yangon',
        'bagan old town': 'Bagan',
        'mandalay hill': 'Mandalay',
        'inle lake': 'Nyaungshwe',
    },
    KH: {
        'bkk1': 'Phnom Penh', 'riverside phnom penh': 'Phnom Penh',
        'russian market': 'Phnom Penh', 'toul tom poung': 'Phnom Penh',
        'daun penh': 'Phnom Penh', 'boeung keng kang': 'Phnom Penh',
        'pub street': 'Siem Reap', 'angkor wat area': 'Siem Reap',
        'siem reap town': 'Siem Reap',
        'sihanoukville beach': 'Sihanoukville', 'otres': 'Sihanoukville',
        'kep beach': 'Kep',
    },
    LA: {
        'luang prabang old town': 'Luang Prabang',
        'vientiane city center': 'Vientiane',
        'vang vieng': 'Vang Vieng',
    },
    NP: {
        'thamel': 'Kathmandu', 'patan': 'Kathmandu', 'bhaktapur': 'Kathmandu',
        'boudhanath': 'Kathmandu', 'swayambhunath': 'Kathmandu',
        'lakeside pokhara': 'Pokhara',
        'namche bazaar': 'Solukhumbu',
    },
    // ── Scandinavia ────────────────────────────────────────────────────────────
    SE: {
        'gamla stan': 'Stockholm', 'sodermalm': 'Stockholm', 'ostermalm': 'Stockholm',
        'vasastan': 'Stockholm', 'kungsholmen': 'Stockholm', 'djurgarden': 'Stockholm',
        'hornstull': 'Stockholm', 'sickla': 'Stockholm', 'lidingo': 'Stockholm',
        'haga': 'Gothenburg', 'linne': 'Gothenburg', 'majorna': 'Gothenburg',
        'haga gothenburg': 'Gothenburg',
        'malmo old town': 'Malmo', 'hyllie': 'Malmo',
    },
    NO: {
        'aker brygge': 'Oslo', 'grunerlokka': 'Oslo', 'frogner': 'Oslo',
        'majorstuen': 'Oslo', 'toyen': 'Oslo', 'sentrum oslo': 'Oslo',
        'gronland': 'Oslo', 'bislett': 'Oslo', 'kampen': 'Oslo',
        'bryggen': 'Bergen', 'nordnes': 'Bergen',
        'trondheim city center': 'Trondheim',
    },
    DK: {
        'norrebro': 'Copenhagen', 'vesterbro': 'Copenhagen', 'frederiksberg': 'Copenhagen',
        'christianshavn': 'Copenhagen', 'indre by': 'Copenhagen',
        'osterbro': 'Copenhagen', 'amager': 'Copenhagen', 'sydhavn': 'Copenhagen',
        'randers': 'Aarhus',
        'aarhus city center': 'Aarhus',
    },
    FI: {
        'kallio': 'Helsinki', 'kamppi': 'Helsinki', 'kruununhaka': 'Helsinki',
        'katajanokka': 'Helsinki', 'ullanlinna': 'Helsinki',
        'toolo': 'Helsinki', 'punavuori': 'Helsinki', 'eira': 'Helsinki',
    },
    // ── Central/Eastern Europe additions ──────────────────────────────────────
    AT: {
        'innere stadt': 'Vienna', 'mariahilf': 'Vienna', 'neubau': 'Vienna',
        'leopoldstadt': 'Vienna', 'wieden': 'Vienna', 'alsergrund': 'Vienna',
        'josefstadt': 'Vienna', 'favoriten': 'Vienna', 'ottakring': 'Vienna',
        'hernals': 'Vienna', 'wahring': 'Vienna',
        'altstadt salzburg': 'Salzburg', 'parsch': 'Salzburg',
        'innsbruck city center': 'Innsbruck',
        'hallstatt village': 'Hallstatt',
    },
    CH: {
        'old town zurich': 'Zurich', 'langstrasse': 'Zurich', 'wiedikon': 'Zurich',
        'seefeld': 'Zurich', 'riesbach': 'Zurich', 'hottingen': 'Zurich',
        'old town bern': 'Bern', 'lorraine': 'Bern',
        'paquis': 'Geneva', 'eaux-vives': 'Geneva', 'plainpalais': 'Geneva',
        'ouchy': 'Lausanne', 'flon': 'Lausanne',
        'lucerne old town': 'Lucerne', 'tribschen': 'Lucerne',
        'basel city center': 'Basel', 'gundeldingen': 'Basel',
        'zermatt village': 'Zermatt',
        'interlaken west': 'Interlaken',
        'montreux waterfront': 'Montreux',
    },
    BE: {
        'grand place': 'Brussels', 'ixelles': 'Brussels', 'saint-gilles': 'Brussels',
        'molenbeek': 'Brussels', 'uccle': 'Brussels', 'schaerbeek': 'Brussels',
        'etterbeek': 'Brussels', 'laeken': 'Brussels',
        'old town bruges': 'Bruges', 'sint-anna': 'Bruges',
        'antwerp city center': 'Antwerp', 'eilandje': 'Antwerp', 'berchem': 'Antwerp',
        'ghent city center': 'Ghent', 'patershol': 'Ghent',
    },
    RO: {
        'old town bucharest': 'Bucharest', 'floreasca': 'Bucharest', 'dorobanti': 'Bucharest',
        'herastrau': 'Bucharest', 'victoriei': 'Bucharest', 'unirii': 'Bucharest',
        'cluj napoca city center': 'Cluj-Napoca', 'manastur': 'Cluj-Napoca',
        'brasov old town': 'Brasov', 'schei': 'Brasov',
    },
    HR: {
        'old town dubrovnik': 'Dubrovnik', 'lapad': 'Dubrovnik', 'babin kuk': 'Dubrovnik',
        'gornji grad': 'Zagreb', 'donji grad': 'Zagreb', 'trnje': 'Zagreb',
        'old town split': 'Split', 'varos': 'Split', 'bacvice': 'Split',
        'stari grad hvar': 'Hvar', 'jelsa': 'Hvar',
        'korcula town': 'Korcula',
        'zadar old town': 'Zadar',
        'rovinj old town': 'Rovinj',
    },
    RS: {
        'stari grad': 'Belgrade', 'savamala': 'Belgrade', 'vracar': 'Belgrade',
        'zemun': 'Belgrade', 'novi beograd': 'Belgrade', 'palilula': 'Belgrade',
        'novi sad old town': 'Novi Sad',
    },
    BG: {
        'city center sofia': 'Sofia', 'lozenets': 'Sofia', 'mladost': 'Sofia',
        'vitosha boulevard': 'Sofia', 'oborishte': 'Sofia',
        'old town plovdiv': 'Plovdiv', 'kapana': 'Plovdiv',
        'varna beach': 'Varna', 'golden sands': 'Varna',
    },
    UA: {
        'podil': 'Kyiv', 'pechersk': 'Kyiv', 'shevchenkivskyi': 'Kyiv',
        'obolon': 'Kyiv', 'svyatoshyn': 'Kyiv',
    },
    // ── Africa additions ───────────────────────────────────────────────────────
    NG: {
        'victoria island': 'Lagos', 'ikoyi': 'Lagos', 'lekki': 'Lagos',
        'vi lagos': 'Lagos', 'yaba': 'Lagos', 'ikeja': 'Lagos',
        'surulere': 'Lagos', 'maryland lagos': 'Lagos', 'ajah': 'Lagos',
        'eko atlantic': 'Lagos', 'oniru': 'Lagos',
        'wuse': 'Abuja', 'maitama': 'Abuja', 'garki': 'Abuja', 'asokoro': 'Abuja',
        'gudu': 'Abuja', 'gwarinpa': 'Abuja',
    },
    GH: {
        'airport residential': 'Accra', 'osu': 'Accra', 'labone': 'Accra',
        'cantonments': 'Accra', 'east legon': 'Accra', 'adabraka': 'Accra',
        'dzorwulu': 'Accra', 'north legon': 'Accra', 'tema': 'Accra',
        'kumasi city center': 'Kumasi',
    },
    TZ: {
        'stone town': 'Zanzibar', 'nungwi': 'Zanzibar', 'kendwa': 'Zanzibar',
        'paje': 'Zanzibar', 'jambiani': 'Zanzibar', 'kiwengwa': 'Zanzibar',
        'msasani': 'Dar es Salaam', 'oyster bay': 'Dar es Salaam',
        'kariakoo': 'Dar es Salaam',
        'arusha city': 'Arusha',
    },
    UG: {
        'kololo': 'Kampala', 'nakasero': 'Kampala', 'kabalagala': 'Kampala',
        'ntinda': 'Kampala', 'muyenga': 'Kampala',
    },
    ET: {
        'bole': 'Addis Ababa', 'kazanchis': 'Addis Ababa', 'piazza addis': 'Addis Ababa',
        'old airport addis': 'Addis Ababa',
    },
    MU: {
        'grand baie': 'Mauritius', 'flic en flac': 'Mauritius', 'trou aux biches': 'Mauritius',
        'blue bay': 'Mauritius', 'belle mare': 'Mauritius', 'mahebourg': 'Mauritius',
        'port louis waterfront': 'Port Louis',
    },
    SC: {
        'beau vallon': 'Mahe', 'victoria seychelles': 'Mahe',
        'anse lazio': 'Praslin', 'anse georgette': 'Praslin',
        'grande anse la digue': 'La Digue',
    },
    MV: {
        'male city': 'Male', 'hulhumale': 'Male',
        'maafushi': 'Maafushi',
    },
    // ── Caribbean / Central America ────────────────────────────────────────────
    DO: {
        'zona colonial': 'Santo Domingo', 'naco': 'Santo Domingo', 'piantini': 'Santo Domingo',
        'bavaro': 'Punta Cana', 'los corales': 'Punta Cana', 'cap cana': 'Punta Cana',
        'las terrenas': 'Las Terrenas',
        'cabarete': 'Cabarete',
    },
    JM: {
        'negril west end': 'Negril', 'seven mile beach': 'Negril',
        'hip strip': 'Montego Bay', 'doctors cave': 'Montego Bay',
        'new kingston': 'Kingston',
        'ocho rios': 'Ocho Rios',
    },
    BS: {
        'nassau downtown': 'Nassau', 'cable beach': 'Nassau', 'paradise island': 'Nassau',
        'grand bahama': 'Freeport',
    },
    CR: {
        'tamarindo': 'Tamarindo', 'nosara': 'Nosara',
        'manuel antonio': 'Quepos', 'la fortuna': 'La Fortuna',
        'escazu': 'San Jose', 'san pedro': 'San Jose', 'sabana': 'San Jose',
        'monteverde': 'Monteverde',
        'jaco beach': 'Jaco',
        'santa teresa cr': 'Santa Teresa',
    },
    GT: {
        'zona viva': 'Guatemala City', 'zona 10': 'Guatemala City', 'zona 4': 'Guatemala City',
        'antigua guatemala': 'Antigua',
        'san marcos la laguna': 'Lake Atitlan',
    },
    PA: {
        'casco viejo': 'Panama City', 'punta pacifica': 'Panama City',
        'marbella': 'Panama City', 'san francisco panama': 'Panama City',
        'el cangrejo': 'Panama City', 'obarrio': 'Panama City',
        'bocas del toro town': 'Bocas del Toro',
    },
    CU: {
        'habana vieja': 'Havana', 'vedado': 'Havana', 'miramar': 'Havana',
        'varadero beach': 'Varadero',
    },
    BB: {
        'bridgetown city': 'Bridgetown',
        'holetown': 'Holetown', 'speightstown': 'Speightstown',
        'oistins': 'Oistins',
    },
    // ── Oceania additions ──────────────────────────────────────────────────────
    FJ: {
        'denarau': 'Nadi', 'port denarau': 'Nadi',
        'suva city center': 'Suva',
        'coral coast': 'Sigatoka',
        'savusavu': 'Savusavu',
    },
    PF: {
        'papeete city': 'Papeete',
        'bora bora motu': 'Bora Bora', 'vaitape': 'Bora Bora',
        'moorea beach': 'Moorea',
    },
    WS: {
        'apia waterfront': 'Apia',
    },
};
