// FastX catalogs hotels by sub-area/neighborhood, not just city name.
// When destinationSearcher(cityName) returns 0 dest codes, querying each neighborhood
// in parallel collects hotel codes actually stored under those areas.
export const CITY_NEIGHBORHOODS: Record<string, string[]> = {
  // ── Japan ────────────────────────────────────────────────────────
  'tokyo':        ['Shinjuku', 'Shibuya', 'Ginza', 'Akihabara', 'Asakusa', 'Ueno', 'Roppongi', 'Ikebukuro', 'Odaiba', 'Marunouchi', 'Harajuku', 'Shinagawa', 'Akasaka', 'Minato', 'Chiyoda', 'Sumida'],
  'tokio':        ['Shinjuku', 'Shibuya', 'Ginza', 'Akihabara', 'Asakusa', 'Roppongi', 'Ikebukuro'],
  'osaka':        ['Namba', 'Umeda', 'Shinsaibashi', 'Dotonbori', 'Osaka Station', 'Tennoji', 'Kyobashi', 'Shin-Osaka'],
  'kyoto':        ['Gion', 'Arashiyama', 'Fushimi', 'Higashiyama', 'Kawaramachi', 'Nijo', 'Kyoto Station', 'Nishiki'],
  'yokohama':     ['Minato Mirai', 'Kannai', 'Yokohama Station', 'Chinatown', 'Motomachi', 'Isezakicho'],
  'sapporo':      ['Susukino', 'Odori', 'Sapporo Station', 'Maruyama', 'Nakajima Park'],
  'nagoya':       ['Nagoya Station', 'Sakae', 'Fushimi', 'Kanayama'],
  'fukuoka':      ['Hakata', 'Tenjin', 'Nakasu', 'Fukuoka Airport', 'Ohori'],
  'hiroshima':    ['Hiroshima Station', 'Naka Ward', 'Peace Memorial', 'Hondori'],
  'nara':         ['Nara Park', 'Kintetsu Nara', 'Todaiji'],
  'okinawa':      ['Naha', 'Chatan', 'Onna', 'Kokusai Street', 'American Village', 'Ginowan'],
  'kanazawa':     ['Kenroku-en', 'Higashi Chaya', 'Kanazawa Station', 'Katamachi'],
  'nikko':        ['Nikko Station', 'Toshogu', 'Chuzenji Lake'],
  'hakone':       ['Hakone Yumoto', 'Gora', 'Togendai', 'Sengokuhara'],
  'kobe':         ['Sannomiya', 'Kitano', 'Harborland', 'Kobe Station', 'Motomachi'],
  'nagasaki':     ['Nagasaki Station', 'Dejima', 'Glover Garden', 'Hamano-machi'],
  'matsuyama':    ['Matsuyama Station', 'Dogo Onsen', 'Otemachi'],
  'kagoshima':    ['Tenmonkan', 'Kagoshima Station', 'Dolphin Port'],
  'sendai':       ['Sendai Station', 'Kokubuncho', 'Ichibancho'],
  // ── South Korea ─────────────────────────────────────────────────
  'seoul':        ['Myeongdong', 'Gangnam', 'Hongdae', 'Itaewon', 'Insadong', 'Sinchon', 'Dongdaemun', 'Mapo', 'Jongno', 'Yongsan', 'Seoul Station', 'Euljiro', 'Hapjeong'],
  'busan':        ['Haeundae', 'Seomyeon', 'Nampo', 'Gwangalli', 'Busan Station', 'Centum City', 'Songdo Beach'],
  'jeju':         ['Jeju City', 'Seogwipo', 'Jungmun', 'Jeju Airport', 'Hallim', 'Aewol'],
  'incheon':      ['Incheon Airport', 'Songdo', 'Bupyeong', 'Jung-gu Incheon', 'Yeonsu'],
  'daejeon':      ['Jung-gu Daejeon', 'Yuseong', 'Daedeok', 'Seo-gu Daejeon', 'Dong-gu Daejeon', 'Daejeon Station', 'Expo Daejeon'],
  'daegu':        ['Jung-gu Daegu', 'Dong-gu Daegu', 'Suseong', 'Dalseo', 'Buk-gu Daegu', 'Daegu Station', 'Dongseongno'],
  'gwangju':      ['Dong-gu Gwangju', 'Seo-gu Gwangju', 'Nam-gu Gwangju', 'Buk-gu Gwangju', 'Gwangsan', 'Gwangju Station'],
  'ulsan':        ['Nam-gu Ulsan', 'Dong-gu Ulsan', 'Buk-gu Ulsan', 'Jung-gu Ulsan', 'Ulsan Station'],
  'suwon':        ['Paldal', 'Yeongtong', 'Jangan', 'Suwon Station', 'Suwon Hwaseong'],
  'jeonju':       ['Wansan', 'Deokjin', 'Jeonju Hanok Village', 'Jeonju Station'],
  'gyeongju':     ['Bulguksa', 'Bomun Lake', 'Gyeongju Station', 'Hwangnam', 'Tumuli Park'],
  'changwon':     ['Masanhoewon', 'Seongsan', 'Uichang', 'Changwon Station'],
  'pohang':       ['Nam-gu Pohang', 'Buk-gu Pohang', 'Pohang Station', 'Yeongil Bay'],
  'chuncheon':    ['Chuncheon Station', 'Myeongdong Chuncheon', 'Soyang Lake', 'Nami Island'],
  'gangneung':    ['Gyeongpo Beach', 'Gangneung Station', 'Jumunjin', 'Anmok Beach'],
  'sokcho':       ['Sokcho Beach', 'Seorak', 'Abai Village', 'Sokcho Station'],
  'yeosu':        ['Yeosu Station', 'Odongdo', 'Dolsan', 'Yeosu Expo'],
  'andong':       ['Andong Station', 'Hahoe Village', 'Andong Mask'],
  'tongyeong':    ['Tongyeong Station', 'Dongpirang', 'Hallyeohaesang'],
  'muju':         ['Muju Resort', 'Muju Station'],
  'pyeongchang':  ['Alpensia', 'Yongpyong', 'Daegwallyeong'],
  // ── China ───────────────────────────────────────────────────────
  'beijing':      ['Chaoyang', 'Dongcheng', 'Xicheng', 'Sanlitun', 'Haidian', 'Guomao', 'Shunyi', 'Wangfujing', 'Tiananmen'],
  'shanghai':     ['Pudong', "Jing'an", 'Xuhui', 'Huangpu', 'Hongkou', 'Changning', 'Lujiazui', 'The Bund', 'Xintiandi'],
  'guangzhou':    ['Tianhe', 'Yuexiu', 'Haizhu', 'Baiyun', 'Zhujiang New Town', 'Guangzhou Station'],
  'shenzhen':     ['Nanshan', 'Futian', 'Luohu', 'Longhua', 'Bao\'an', 'Shekou'],
  'chengdu':      ['Jinjiang', 'Wuhou', 'Qingyang', 'Chunxi Road', 'Tianfu Square', 'Kuanzhai Alley'],
  'xi\'an':       ['Bell Tower', 'Muslim Quarter', 'Yanta', "Xi'an Station", 'South Gate'],
  'hangzhou':     ['West Lake', 'Binjiang', 'Gongshu', 'Xixi Wetlands', 'Longjing'],
  'nanjing':      ['Xinjiekou', 'Confucius Temple', 'Xuanwu', 'Nanjing Station'],
  'qingdao':      ['Shinan', 'Badaguan', 'May Fourth Square', 'Laoshan', 'Qingdao Station'],
  'wuhan':        ['Wuchang', 'Hankou', 'Yellow Crane Tower', 'Wuhan Station'],
  'chongqing':    ['Jiefangbei', 'Jiulongpo', 'Shapingba', 'Chaotianmen', 'Hongyadong'],
  'kunming':      ['Guanshang', 'Wuhua', 'Green Lake', 'Kunming Station'],
  'guilin':       ['Guilin Station', 'Two Rivers Four Lakes', 'Elephant Trunk Hill', 'Yangshuo'],
  'yangshuo':     ['West Street', 'Yangshuo County', 'Moon Hill'],
  'lijiang':      ['Old Town Lijiang', 'Shuhe', 'Black Dragon Pool'],
  'zhangjiajie':  ['Zhangjiajie National Park', 'Wulingyuan', 'Tianmen Mountain'],
  'harbin':       ['Daoli', 'Nangang', 'Saint Sophia', 'Harbin Station'],
  'sanya':        ['Yalong Bay', 'Sanya Bay', 'Dadonghai', 'Sanya City'],
  'haikou':       ['Longhua', 'Meilan', 'Haikou Station'],
  'xiamen':       ['Gulangyu', 'Siming', 'Jimei', 'Xiamen Station'],
  'macau':        ['Cotai', 'Taipa', 'Coloane', 'Senado Square', 'Macau Peninsula'],
  // ── Hong Kong ───────────────────────────────────────────────────
  'hong kong':    ['Kowloon', 'Tsim Sha Tsui', 'Causeway Bay', 'Central', 'Mong Kok', 'Wan Chai', 'Admiralty', 'Tung Chung', 'Sha Tin'],
  // ── Taiwan ──────────────────────────────────────────────────────
  'taipei':       ['Zhongshan', "Da'an", 'Xinyi', 'Zhongzheng', 'Wanhua', 'Songshan', 'Shilin', 'Ximending'],
  'taichung':     ['Xitun', 'West District', 'Fengjia', 'Central Taichung'],
  'tainan':       ['West Central', 'Anping', 'Tainan Station'],
  'kaohsiung':    ['Lingya', 'Xinxing', 'Zuoying', 'Cijin Island', 'Kaohsiung Station'],
  'hualien':      ['Hualien City', 'Taroko', 'Hualien Station'],
  'kenting':      ['Kenting Beach', 'Hengchun', 'Baisha Bay'],
  // ── Southeast Asia — Thailand ────────────────────────────────────
  'bangkok':      ['Sukhumvit', 'Silom', 'Siam', 'Khaosan', 'Asok', 'Nana', 'Ratchadamri', 'Pratunam', 'Bangna', 'Chatuchak', 'Thonburi', 'Ari', 'Onnut'],
  'phuket':       ['Patong', 'Kata', 'Karon', 'Surin', 'Bang Tao', 'Rawai', 'Kamala', 'Phuket Town', 'Nai Harn', 'Mai Khao', 'Laguna'],
  'chiang mai':   ['Nimman', 'Old City', 'Santitham', 'Chang Klan', 'Nimmanhaemin', 'Doi Suthep'],
  'pattaya':      ['Jomtien', 'Central Pattaya', 'North Pattaya', 'Naklua', 'Bang Saray', 'South Pattaya'],
  'krabi':        ['Ao Nang', 'Railay', 'Klong Muang', 'Krabi Town', 'Koh Lanta'],
  'koh samui':    ['Chaweng', 'Lamai', 'Bophut', 'Maenam', 'Choeng Mon', 'Fisherman\'s Village'],
  'hua hin':      ['Hua Hin Beach', 'Cicada Market', 'Khao Takiab', 'Hua Hin Station'],
  'koh phi phi':  ['Ton Sai Bay', 'Phi Phi Don', 'Long Beach'],
  'koh chang':    ['White Sand Beach', 'Lonely Beach', 'Klong Prao'],
  'chiang rai':   ['Chiang Rai City', 'White Temple', 'Night Bazaar Chiang Rai'],
  'ayutthaya':    ['Ayutthaya Historical Park', 'Ayutthaya Station'],
  // ── Southeast Asia — Vietnam ────────────────────────────────────
  'ho chi minh':  ['District 1', 'District 3', 'Bui Vien', 'Pham Ngu Lao', 'Nguyen Hue', 'Dong Khoi', 'Tan Binh', 'Binh Thanh', 'Phu My Hung'],
  'saigon':       ['District 1', 'Bui Vien', 'Pham Ngu Lao'],
  'hanoi':        ['Hoan Kiem', 'Old Quarter', 'Ba Dinh', 'Dong Da', 'Tay Ho', 'West Lake', 'Cau Giay', 'Hoan Kiem Lake'],
  'da nang':      ['My Khe Beach', 'An Thuong', 'Da Nang Beach', 'Marble Mountains', 'Son Tra'],
  'hoi an':       ['Old Town', 'An Bang Beach', 'Cua Dai', 'Cam Thanh'],
  'nha trang':    ['Tran Phu', 'Nha Trang Beach', 'Loc Tho', 'Vinpearl'],
  'phu quoc':     ['Long Beach', 'Duong Dong', 'Ong Lang', 'An Thoi', 'Phu Quoc Town'],
  'vung tau':     ['Front Beach', 'Back Beach', 'Vung Tau City'],
  'ha long':      ['Ha Long City', 'Bai Chay', 'Ha Long Bay'],
  'sapa':         ['Sapa Town', 'Fansipan', 'Cat Cat Village'],
  'hue':          ['Imperial City', 'Dong Ba', 'An Dinh Palace', 'Hue Station'],
  'mui ne':       ['Mui Ne Beach', 'Phan Thiet', 'Fairy Stream'],
  'can tho':      ['Ninh Kieu', 'Cai Rang Market', 'Can Tho City'],
  // ── Southeast Asia — Philippines ────────────────────────────────
  'manila':       ['Makati', 'BGC', 'Taguig', 'Ortigas', 'Pasay', 'Ermita', 'Malate', 'Quezon City', 'Pasig', 'Intramuros', 'Binondo'],
  'cebu':         ['Cebu City', 'Mactan', 'Lapu-Lapu', 'Mandaue', 'IT Park', 'Lahug', 'Ayala Center'],
  'boracay':      ['White Beach', 'Station 1', 'Station 2', 'Station 3', 'Bulabog', 'Diniwid'],
  'palawan':      ['El Nido', 'Port Barton', 'Coron', 'Puerto Princesa'],
  'el nido':      ['El Nido Town', 'Nacpan', 'Corong Corong', 'Las Cabanas'],
  'davao':        ['Davao City', 'Ecoland', 'Bajada', 'Matina', 'Toril'],
  'bohol':        ['Panglao', 'Alona Beach', 'Tagbilaran', 'Chocolate Hills'],
  'siargao':      ['General Luna', 'Cloud 9', 'Dapa'],
  'batangas':     ['Anilao', 'Mabini', 'Batangas City'],
  'clark':        ['Clark Freeport', 'Angeles City', 'Pampanga'],
  'iloilo':       ['Iloilo City', 'Diversion Road', 'SM Iloilo'],
  'cagayan de oro': ['Centrio', 'CDO Station', 'Camaman-an'],
  'zamboanga':    ['Zamboanga City', 'Rio Hondo', 'Paseo del Mar'],
  'subic':        ['Subic Bay', 'Olongapo', 'Barretto'],
  'tagaytay':     ['Tagaytay Ridge', 'Taal Vista', 'Sky Ranch'],
  'baguio':       ['Session Road', 'Burnham Park', 'Camp John Hay', 'Baguio City'],
  // ── Southeast Asia — Indonesia ──────────────────────────────────
  'bali':         ['Kuta', 'Seminyak', 'Ubud', 'Canggu', 'Nusa Dua', 'Jimbaran', 'Legian', 'Sanur', 'Uluwatu', 'Denpasar', 'Amed', 'Lovina'],
  'jakarta':      ['SCBD', 'Sudirman', 'Menteng', 'Kemang', 'Kota Tua', 'Kuningan', 'Kelapa Gading', 'Pluit'],
  'lombok':       ['Senggigi', 'Gili Trawangan', 'Gili Air', 'Kuta Lombok', 'Mataram', 'Gili Meno'],
  'yogyakarta':   ['Malioboro', 'Prawirotaman', 'Kraton', 'Sleman', 'Borobudur'],
  'surabaya':     ['Genteng', 'Gubeng', 'Wonokromo', 'Surabaya Station'],
  'bandung':      ['Dago', 'Pasteur', 'Braga', 'Bandung Station', 'Cihampelas'],
  'medan':        ['Medan Petisah', 'Medan Baru', 'Medan Station', 'Sun Plaza'],
  'makassar':     ['Losari Beach', 'Panakukang', 'Makassar Station'],
  'manado':       ['Manado City', 'Bunaken', 'Boulevard'],
  'labuan bajo':  ['Labuan Bajo Town', 'Komodo', 'Pink Beach'],
  'raja ampat':   ['Sorong', 'Waisai', 'Pianemo'],
  'komodo':       ['Komodo Island', 'Rinca Island', 'Labuan Bajo'],
  'nusa penida':  ['Crystal Bay', 'Kelingking', 'Broken Beach'],
  'gili islands': ['Gili Trawangan', 'Gili Air', 'Gili Meno'],
  // ── Southeast Asia — Malaysia ───────────────────────────────────
  'kuala lumpur': ['Bukit Bintang', 'KLCC', 'Chinatown', 'Bangsar', 'Mont Kiara', 'Chow Kit', 'Petaling Jaya', 'Brickfields', 'Pavilion'],
  'penang':       ['George Town', 'Batu Ferringhi', 'Gurney', 'Komtar', 'Little India Penang'],
  'langkawi':     ['Pantai Cenang', 'Kuah', 'Pantai Tengah', 'Datai Bay', 'Tanjung Rhu'],
  'kota kinabalu': ['City Centre', 'Likas', 'Tanjung Aru', 'Gaya Street', 'Kota Belud'],
  'johor bahru':  ['JB City', 'Danga Bay', 'Bukit Indah', 'Larkin'],
  'malacca':      ['Jonker Street', 'Dutch Square', 'Bukit China', 'Malacca City'],
  'melaka':       ['Jonker Street', 'Dutch Square', 'Bukit China', 'Melaka City'],
  'kuching':      ['Kuching Waterfront', 'Old Town Kuching', 'Padungan'],
  'ipoh':         ['Old Town Ipoh', 'New Town Ipoh', 'Ipoh Station'],
  'cameron highlands': ['Brinchang', 'Tanah Rata', 'Ringlet'],
  'kota bharu':   ['Chinatown Kota Bharu', 'Pasar Besar Siti Khadijah', 'Kota Bharu City'],
  'tioman':       ['Tekek', 'Air Batang', 'Salang'],
  'perhentian':   ['Perhentian Besar', 'Perhentian Kecil', 'Coral Bay'],
  // ── Southeast Asia — Singapore ──────────────────────────────────
  'singapore':    ['Orchard', 'Marina Bay', 'Clarke Quay', 'Bugis', 'Sentosa', 'Chinatown', 'Little India', 'Geylang', 'Tanjong Pagar', 'Dempsey'],
  // ── Southeast Asia — Myanmar ────────────────────────────────────
  'yangon':       ['Dagon', 'Downtown Yangon', 'Sule Pagoda', 'Chinatown Yangon'],
  'bagan':        ['Old Bagan', 'New Bagan', 'Nyaung-U'],
  'mandalay':     ['Mandalay City', 'Mandalay Palace', 'Zegyo Market'],
  'inle lake':    ['Nyaungshwe', 'Inle Lake Town', 'Indein'],
  // ── Southeast Asia — Cambodia ───────────────────────────────────
  'siem reap':    ['Pub Street', 'Old Market', 'Angkor Wat', 'Charles de Gaulle'],
  'phnom penh':   ['Daun Penh', 'BKK1', 'Riverside Phnom Penh', 'Toul Tompoung'],
  // ── Southeast Asia — Laos ───────────────────────────────────────
  'luang prabang': ['Luang Prabang Old Town', 'Ban Xieng Mouane', 'Mekong Riverside'],
  'vientiane':    ['Chanthaboury', 'Patuxai', 'Vientiane Center'],
  // ── Southeast Asia — Brunei ─────────────────────────────────────
  'bandar seri begawan': ['Kampong Ayer', 'Gadong', 'Bandar Seri Begawan City'],
  // ── South Asia — India ──────────────────────────────────────────
  'delhi':        ['Connaught Place', 'Karol Bagh', 'Paharganj', 'Aerocity', 'Dwarka', 'Noida', 'Gurgaon', 'Lajpat Nagar', 'Chandni Chowk'],
  'new delhi':    ['Connaught Place', 'Karol Bagh', 'Paharganj', 'Aerocity', 'Gurgaon', 'Nehru Place'],
  'mumbai':       ['Bandra', 'Colaba', 'Andheri', 'Juhu', 'Powai', 'Dadar', 'Lower Parel', 'Worli', 'Fort Mumbai', 'Santacruz'],
  'goa':          ['Calangute', 'Baga', 'Anjuna', 'Panaji', 'Vagator', 'Palolem', 'Candolim', 'Arambol', 'Colva', 'Morjim'],
  'jaipur':       ['MI Road', 'Sindhi Camp', 'Civil Lines', 'Pink City', 'Bani Park', 'Malviya Nagar', 'Vaishali Nagar'],
  'bangalore':    ['MG Road', 'Koramangala', 'Indiranagar', 'Whitefield', 'Brigade Road', 'Electronic City', 'Jayanagar'],
  'agra':         ['Taj Ganj', 'Sadar Bazaar', 'Fatehabad Road', 'Agra Cantonment'],
  'varanasi':     ['Dashashwamedh Ghat', 'Assi Ghat', 'Godaulia', 'Sarnath'],
  'hyderabad':    ['Banjara Hills', 'Jubilee Hills', 'Secunderabad', 'Charminar', 'Madhapur', 'HITEC City'],
  'chennai':      ['Anna Nagar', 'T Nagar', 'Egmore', 'Nungambakkam', 'Adyar', 'Marina Beach'],
  'kolkata':      ['Park Street', 'Salt Lake', 'New Town', 'Howrah', 'Ballygunge', 'Esplanade'],
  'pune':         ['Koregaon Park', 'Baner', 'Hinjewadi', 'Shivajinagar', 'Hadapsar'],
  'ahmedabad':    ['Navrangpura', 'Satellite', 'Paldi', 'Maninagar', 'SG Highway'],
  'amritsar':     ['Golden Temple', 'Lawrence Road', 'Civil Lines Amritsar'],
  'udaipur':      ['City Palace Udaipur', 'Fateh Sagar', 'Pichola Lake', 'Hiran Magri'],
  'jodhpur':      ['Clock Tower', 'Mehrangarh', 'Ratanada'],
  'manali':       ['Mall Road Manali', 'Old Manali', 'Solang Valley'],
  'shimla':       ['Mall Road Shimla', 'Ridge', 'Lakkar Bazaar'],
  'mysore':       ['Mysore Palace', 'Chamundi Hill', 'VV Mohalla'],
  'pondicherry':  ['French Quarter', 'White Town', 'Promenade Beach'],
  'kochi':        ['Fort Kochi', 'Ernakulam', 'Mattancherry', 'Marine Drive Kochi'],
  'munnar':       ['Munnar Town', 'Top Station', 'Eravikulam'],
  'dharamshala':  ['McLeod Ganj', 'Kotwali Bazaar', 'Forsyth Ganj'],
  'rishikesh':    ['Laxman Jhula', 'Ram Jhula', 'Tapovan'],
  // ── South Asia — Sri Lanka ──────────────────────────────────────
  'colombo':      ['Colombo 1', 'Colombo 3', 'Colombo 7', 'Fort', 'Kollupitiya', 'Bambalapitiya'],
  'kandy':        ['Kandy City', 'Temple of the Tooth', 'Peradeniya'],
  'galle':        ['Galle Fort', 'Unawatuna', 'Hikkaduwa'],
  'negombo':      ['Negombo Beach', 'Negombo Town', 'Lewis Place'],
  'ella':         ['Ella Rock', 'Nine Arch Bridge', 'Ella Town'],
  'sigiriya':     ['Sigiriya Rock', 'Dambulla', 'Habarana'],
  // ── South Asia — Nepal ──────────────────────────────────────────
  'kathmandu':    ['Thamel', 'Patan', 'Bhaktapur', 'Boudhanath', 'Pashupatinath', 'Durbar Square'],
  'pokhara':      ['Lakeside', 'Damside', 'Phewa Lake', 'Bagar'],
  // ── South Asia — Maldives ───────────────────────────────────────
  'male':         ['Male City', 'Hulhumale', 'Maafushi'],
  'maafushi':     ['Maafushi Island', 'Maafushi Beach'],
  // ── South Asia — Bangladesh ─────────────────────────────────────
  'dhaka':        ['Gulshan', 'Banani', 'Dhanmondi', 'Motijheel', 'Old Dhaka'],
  'chittagong':   ['Agrabad', 'GEC Circle', 'Patenga Beach'],
  // ── South Asia — Pakistan ───────────────────────────────────────
  'karachi':      ['Clifton', 'DHA Karachi', 'Saddar', 'Gulshan-e-Iqbal'],
  'lahore':       ['Gulberg', 'DHA Lahore', 'Model Town', 'Old City Lahore'],
  'islamabad':    ['F-6', 'F-7', 'F-8', 'Blue Area', 'G-11'],
  // ── Middle East ─────────────────────────────────────────────────
  'dubai':        ['Downtown', 'Marina', 'JBR', 'Deira', 'Jumeirah', 'Business Bay', 'Bur Dubai', 'Palm Jumeirah', 'DIFC', 'Al Barsha', 'Mirdif'],
  'abu dhabi':    ['Corniche', 'Yas Island', 'Saadiyat', 'Al Raha', 'Khalidiyah', 'Tourist Club Area'],
  'doha':         ['The Pearl', 'West Bay', 'Corniche', 'Al Sadd', 'Souq Waqif', 'Katara'],
  'riyadh':       ['Al Olaya', 'Al Malaz', 'Diplomatic Quarter', 'Al Faisaliah', 'Sulaimaniyah'],
  'jeddah':       ['Al Balad', 'Al Andalus', 'Al Hamra', 'Corniche Jeddah', 'King Fahd Road'],
  'muscat':       ['Muttrah', 'Al Mouj', 'Qurum', 'Shatti Al Qurum', 'Old Muscat'],
  'kuwait city':  ['Sharq', 'Salmiya', 'Hawalli', 'Fahaheel'],
  'manama':       ['Diplomatic Area', 'Seef District', 'Amwaj Islands', 'Adliya'],
  'beirut':       ['Hamra', 'Gemmayzeh', 'Mar Mikhael', 'Raouche', 'Downtown Beirut'],
  'amman':        ['Abdoun', 'Sweifieh', 'Rainbow Street', 'Aqaba', 'Downtown Amman'],
  'tel aviv':     ['Florentin', 'Neve Tzedek', 'Dizengoff', 'Jaffa', 'Rothschild Boulevard'],
  'jerusalem':    ['Old City Jerusalem', 'Mamilla', 'German Colony Jerusalem', 'Rehavia'],
  'istanbul':     ['Sultanahmet', 'Taksim', 'Beyoglu', 'Besiktas', 'Sisli', 'Kadikoy', 'Fatih', 'Karakoy', 'Galata'],
  'ankara':       ['Kizilay', 'Cankaya', 'Ulus', 'Kavaklidere'],
  'cappadocia':   ['Goreme', 'Urgup', 'Avanos', 'Nevsehir'],
  'antalya':      ['Kaleici', 'Lara', 'Konyaalti', 'Belek', 'Side'],
  'bodrum':       ['Bodrum Center', 'Gumusluk', 'Turgutreis', 'Yalikavak'],
  'izmir':        ['Alsancak', 'Konak', 'Bornova', 'Buca'],
  'marmaris':     ['Marmaris Center', 'Icmeler', 'Armutalan'],
  // ── Africa ──────────────────────────────────────────────────────
  'cairo':        ['Zamalek', 'Maadi', 'Heliopolis', 'Downtown Cairo', 'Giza'],
  'marrakech':    ['Medina', 'Gueliz', 'Palmeraie', 'Hivernage'],
  'casablanca':   ['Ain Diab', 'Maarif', 'CIL', 'Downtown Casablanca'],
  'nairobi':      ['Westlands', 'Karen', 'Kilimani', 'Upper Hill', 'CBD Nairobi'],
  'cape town':    ['V&A Waterfront', 'Sea Point', 'Green Point', 'Camps Bay', 'Boulders Beach', 'CBD Cape Town'],
  'johannesburg': ['Sandton', 'Rosebank', 'Melrose Arch', 'Maboneng', 'Morningside'],
  'zanzibar':     ['Stone Town', 'Nungwi', 'Kendwa', 'Paje', 'Jambiani'],
  'accra':        ['Osu', 'Cantonments', 'Airport Residential', 'Labone'],
  'lagos':        ['Victoria Island', 'Ikoyi', 'Lekki', 'Ikeja'],
  'addis ababa':  ['Bole', 'Kazanchis', 'Piassa', 'CMC'],
  'dar es salaam': ['Masaki', 'Oyster Bay', 'Msasani', 'City Centre DSM'],
  'kigali':       ['Kiyovu', 'Kimihurura', 'Remera', 'Nyarutarama'],
  'lusaka':       ['Kabulonga', 'Woodlands', 'Northmead', 'Cairo Road'],
  'harare':       ['Avondale', 'Borrowdale', 'Msasa', 'CBD Harare'],
  'tunis':        ['La Marsa', 'Les Berges du Lac', 'Medina Tunis', 'Gammarth'],
  'fez':          ['Fez Medina', 'Ville Nouvelle Fez', 'Batha'],
  'essaouira':    ['Medina Essaouira', 'Moulay Hassan Square'],
  'sharm el sheikh': ['Naama Bay', 'Soho Square', 'Old Market Sharm'],
  'hurghada':     ['El Dahar', 'New Marina', 'Sakkala', 'Makadi Bay'],
  'luxor':        ['West Bank Luxor', 'East Bank Luxor', 'Karnak'],
  'aswan':        ['Aswan City', 'Philae', 'Elephantine Island'],
  // ── Europe ──────────────────────────────────────────────────────
  'london':       ['Westminster', 'Covent Garden', 'Kensington', 'Shoreditch', 'Mayfair', 'Canary Wharf', 'Camden', 'Paddington', 'Heathrow', 'City of London', 'Southwark', 'Notting Hill'],
  'paris':        ['Marais', 'Saint-Germain', 'Montmartre', 'Champs-Elysees', 'Opera', 'Bastille', 'Latin Quarter', 'Pigalle', 'Oberkampf', 'Batignolles'],
  'rome':         ['Colosseum', 'Vatican', 'Trastevere', 'Campo de Fiori', 'Navona', 'Spanish Steps', 'Termini', 'Prati', 'Testaccio'],
  'barcelona':    ['Gothic Quarter', 'Eixample', 'Gracia', 'El Born', 'Barceloneta', 'Sagrada Familia', 'Sants', 'Poblenou'],
  'amsterdam':    ['Jordaan', 'De Pijp', 'Centrum', 'Museum Quarter', 'Leidseplein', 'Vondelpark', 'Oud-West'],
  'berlin':       ['Mitte', 'Prenzlauer Berg', 'Kreuzberg', 'Friedrichshain', 'Charlottenburg', 'Schoneberg', 'Neukölln'],
  'madrid':       ['Sol', 'Salamanca', 'Malasana', 'Chueca', 'La Latina', 'Retiro', 'Lavapies', 'Embajadores'],
  'prague':       ['Old Town', 'New Town', 'Mala Strana', 'Vinohrady', 'Zizkov', 'Holesovice'],
  'vienna':       ['Innere Stadt', 'Mariahilf', 'Josefstadt', 'Leopoldstadt', 'Favoriten', 'Naschmarkt'],
  'budapest':     ['District V', 'District VII', 'Pest', 'Buda', 'Castle District', 'Andrassy', 'Ruin Bar District'],
  'lisbon':       ['Alfama', 'Bairro Alto', 'Chiado', 'Belem', 'Mouraria', 'Intendente', 'Principe Real'],
  'athens':       ['Plaka', 'Monastiraki', 'Syntagma', 'Kolonaki', 'Psiri', 'Koukaki', 'Exarchia'],
  'milan':        ['Duomo', 'Brera', 'Navigli', 'Porta Romana', 'Isola', 'Porta Venezia'],
  'florence':     ['Santa Croce', 'Oltrarno', 'San Lorenzo', 'Duomo Florence', 'Santa Maria Novella'],
  'venice':       ['San Marco', 'Cannaregio', 'Dorsoduro', 'Castello', 'Santa Croce Venice', 'Lido di Venezia'],
  'naples':       ['Centro Storico Naples', 'Chiaia', 'Posillipo', 'Vomero'],
  'zurich':       ['Altstadt', 'Langstrasse', 'Zurich West', 'Seefeld', 'Oerlikon'],
  'geneva':       ['Old Town Geneva', 'Eaux-Vives', 'Plainpalais'],
  'brussels':     ['Ixelles', 'Saint-Gilles', 'Grand Place', 'Uccle', 'European Quarter Brussels'],
  'copenhagen':   ['Nørreport', 'Vesterbro', 'Nørrebro', 'Frederiksberg', 'Indre By'],
  'stockholm':    ['Gamla Stan', 'Södermalm', 'Östermalm', 'Vasastan', 'Kungsholmen'],
  'oslo':         ['Aker Brygge', 'Grunerlokka', 'Frogner', 'St Hanshaugen'],
  'helsinki':     ['Kamppi', 'Kallio', 'Töölö', 'Punavuori'],
  'reykjavik':    ['City Centre Reykjavik', '101 Reykjavik', 'Laugavegur'],
  'warsaw':       ['Old Town Warsaw', 'Mokotow', 'Ochota', 'Praga Polnoc'],
  'krakow':       ['Kazimierz', 'Old Town Krakow', 'Podgorze', 'Nowa Huta'],
  'wroclaw':      ['Old Town Wroclaw', 'Srodmiescie', 'Krzyki'],
  'bucharest':    ['Floreasca', 'Dorobanti', 'Old Town Bucharest', 'Sector 1'],
  'sofia':        ['City Centre Sofia', 'Lozenets', 'Student City', 'Vitosha'],
  'zagreb':       ['Upper Town Zagreb', 'Donji Grad Zagreb', 'Gornji Grad', 'Maksimir'],
  'dubrovnik':    ['Old Town Dubrovnik', 'Lapad', 'Pile', 'Placa'],
  'split':        ['Old Town Split', 'Diocletian\'s Palace', 'Bacvice', 'Znjan'],
  'tallinn':      ['Old Town Tallinn', 'Kalamaja', 'Toompea'],
  'riga':         ['Old Town Riga', 'Art Nouveau District', 'Teika'],
  'vilnius':      ['Old Town Vilnius', 'Uzupis', 'New City Centre'],
  'valletta':     ['Sliema', 'St Julian\'s', 'Bugibba', 'Mellieha'],
  'nicosia':      ['Old City Nicosia', 'Limassol', 'Paphos', 'Ayia Napa'],
  'limassol':     ['Old Port Limassol', 'Germasogeia', 'Amathus'],
  'santorini':    ['Fira', 'Oia', 'Imerovigli', 'Perissa', 'Kamari'],
  'mykonos':      ['Mykonos Town', 'Psarou', 'Paradise Beach', 'Ornos'],
  'thessaloniki': ['Aristotelous', 'Ladadika', 'Ano Poli', 'Kalamaria'],
  'porto':        ['Ribeira', 'Cedofeita', 'Bonfim', 'Foz do Douro'],
  'seville':      ['Santa Cruz', 'Triana', 'El Centro Seville', 'Macarena'],
  'granada':      ['Albaicin', 'Sacromonte', 'Centro Granada'],
  'malaga':       ['Centro Historico Malaga', 'Soho Malaga', 'Pedregalejo'],
  'palma':        ['Old Town Palma', 'Santa Catalina', 'El Arenal', 'Playa de Palma'],
  'ibiza':        ['Ibiza Town', 'San Antonio', 'Playa den Bossa', 'Santa Eulalia'],
  'nice':         ['Promenade des Anglais', 'Old Town Nice', 'Cimiez'],
  'lyon':         ['Vieux Lyon', 'Croix-Rousse', 'Part-Dieu', 'Confluence'],
  'marseille':    ['Vieux-Port', 'Le Panier', 'Prado'],
  'munich':       ['Marienplatz', 'Schwabing', 'Maxvorstadt', 'Glockenbach', 'Haidhausen'],
  'hamburg':      ['Altona', 'HafenCity', 'Reeperbahn', 'Eimsbüttel', 'Hamburg City'],
  'frankfurt':    ['Sachsenhausen', 'Bockenheim', 'Innenstadt Frankfurt', 'Westend'],
  'cologne':      ['Altstadt-Nord', 'Ehrenfeld', 'Deutz', 'Belgian Quarter'],
  'edinburgh':    ['Old Town Edinburgh', 'New Town Edinburgh', 'Leith', 'Grassmarket'],
  'dublin':       ['Temple Bar', 'Docklands', 'Rathmines', 'Ballsbridge'],
  // ── Americas — USA ──────────────────────────────────────────────
  'new york':     ['Manhattan', 'Midtown', 'Times Square', 'Brooklyn', 'Chelsea', 'SoHo', 'Upper West Side', 'Financial District', 'Lower East Side', 'Harlem', 'Queens'],
  'los angeles':  ['Hollywood', 'Santa Monica', 'Beverly Hills', 'West Hollywood', 'Downtown LA', 'Venice', 'Koreatown', 'Silver Lake'],
  'miami':        ['South Beach', 'Brickell', 'Wynwood', 'Miami Beach', 'Downtown Miami', 'Doral', 'Coral Gables', 'Coconut Grove'],
  'las vegas':    ['The Strip', 'Downtown Vegas', 'Henderson', 'Paradise', 'Summerlin'],
  'san francisco': ['Union Square', 'Fisherman\'s Wharf', 'Mission', 'SoMa', 'North Beach', 'Haight-Ashbury', 'Castro'],
  'chicago':      ['The Loop', 'River North', 'Magnificent Mile', 'Wicker Park', 'Lincoln Park', 'Gold Coast Chicago'],
  'boston':       ['Back Bay', 'Beacon Hill', 'South End', 'Cambridge', 'Downtown Boston'],
  'washington dc': ['Georgetown', 'Dupont Circle', 'Capitol Hill', 'Logan Circle', 'Navy Yard'],
  'seattle':      ['Capitol Hill', 'Belltown', 'Pike Place', 'South Lake Union', 'Pioneer Square'],
  'houston':      ['Galleria', 'Midtown Houston', 'Montrose', 'Museum District Houston'],
  'dallas':       ['Uptown Dallas', 'Deep Ellum', 'Downtown Dallas', 'Bishop Arts'],
  'atlanta':      ['Midtown Atlanta', 'Buckhead', 'Old Fourth Ward', 'Inman Park'],
  'phoenix':      ['Downtown Phoenix', 'Scottsdale', 'Tempe', 'Old Town Scottsdale'],
  'denver':       ['LoDo', 'Capitol Hill Denver', 'Five Points', 'Cherry Creek'],
  'nashville':    ['Broadway Nashville', 'Germantown', 'East Nashville', '12 South'],
  'new orleans':  ['French Quarter', 'Garden District', 'Marigny', 'Warehouse District'],
  'san diego':    ['Gaslamp Quarter', 'La Jolla', 'Pacific Beach', 'Old Town San Diego'],
  'orlando':      ['Walt Disney World', 'International Drive', 'Universal Orlando', 'Downtown Orlando'],
  'honolulu':     ['Waikiki', 'Ala Moana', 'Kaimuki', 'Manoa'],
  'maui':         ['Lahaina', 'Kaanapali', 'Wailea', 'Paia'],
  'kauai':        ['Poipu', 'Princeville', 'Kapaa', 'Lihue'],
  'big island':   ['Kailua-Kona', 'Hilo', 'Waikoloa', 'Volcano'],
  'portland':     ['Pearl District', 'Mississippi Avenue', 'Alberta Arts District', 'Hawthorne'],
  'minneapolis':  ['Downtown Minneapolis', 'Uptown Minneapolis', 'North Loop'],
  'san antonio':  ['River Walk', 'Alamo Plaza', 'Pearl District SA'],
  'salt lake city': ['Downtown SLC', 'Sugar House', 'Park City'],
  // ── Americas — Canada ───────────────────────────────────────────
  'toronto':      ['Downtown', 'Yorkville', 'Distillery', 'King West', 'Midtown', 'North York', 'Kensington Market', 'Queen West'],
  'vancouver':    ['Downtown Vancouver', 'Gastown', 'Yaletown', 'Kitsilano', 'Commercial Drive'],
  'montreal':     ['Old Montreal', 'Plateau', 'Mile End', 'Downtown Montreal', 'Saint-Laurent'],
  'calgary':      ['Downtown Calgary', 'Beltline', 'Kensington Calgary'],
  'ottawa':       ['ByWard Market', 'Glebe', 'Centretown', 'Westboro'],
  'quebec city':  ['Old Quebec', 'Plains of Abraham', 'Saint-Roch'],
  'banff':        ['Banff Town', 'Lake Louise', 'Canmore'],
  'victoria':     ['Inner Harbour', 'Oak Bay', 'James Bay'],
  'whistler':     ['Whistler Village', 'Blackcomb', 'Alta Lake'],
  'niagara falls': ['Fallsview', 'Clifton Hill', 'Old Town Niagara'],
  // ── Americas — Mexico ───────────────────────────────────────────
  'mexico city':  ['Polanco', 'Condesa', 'Roma Norte', 'Centro Historico', 'Coyoacan', 'Santa Fe'],
  'cancun':       ['Hotel Zone', 'Centro Cancun', 'Puerto Morelos', 'Playa del Carmen', 'Tulum'],
  'guadalajara':  ['Centro Guadalajara', 'Zapopan', 'Tlaquepaque'],
  'monterrey':    ['Centro Monterrey', 'San Pedro Garza Garcia', 'Barrio Antiguo'],
  'tulum':        ['Tulum Beach', 'Tulum Town', 'Tulum Ruins'],
  'puerto vallarta': ['Zona Romantica', 'Marina Vallarta', 'Old Town Vallarta'],
  'oaxaca':       ['Centro Historico Oaxaca', 'Jalatlaco', 'San Felipe del Agua'],
  'san miguel de allende': ['Centro San Miguel', 'Zona Centro'],
  'cabo san lucas': ['Cabo Marina', 'Medano Beach', 'Pedregal'],
  'playa del carmen': ['Quinta Avenida', 'Playacar', 'Centro Playa'],
  'merida':       ['Centro Merida', 'Paseo de Montejo', 'Polanco Merida'],
  // ── Americas — Caribbean ────────────────────────────────────────
  'havana':       ['Vedado', 'Miramar', 'Habana Vieja', 'Playa Havana'],
  'santo domingo': ['Zona Colonial', 'Piantini', 'Naco'],
  'san juan':     ['Old San Juan', 'Condado', 'Miramar PR', 'Isla Verde'],
  'nassau':       ['Cable Beach', 'Paradise Island', 'Downtown Nassau'],
  'bridgetown':   ['Hastings', 'Worthing', 'Holetown', 'Speightstown'],
  'kingston':     ['New Kingston', 'Half Way Tree', 'Barbican'],
  // ── Americas — South America ────────────────────────────────────
  'bogota':       ['Candelaria', 'Chapinero', 'Zona Rosa', 'Usaquen'],
  'medellin':     ['El Poblado', 'Laureles', 'Envigado', 'La Candelaria Medellin'],
  'cartagena':    ['Walled City', 'Bocagrande', 'Getsemani', 'Castillogrande'],
  'lima':         ['Miraflores', 'Barranco', 'San Isidro', 'Surco'],
  'cusco':        ['San Blas', 'Centro Cusco', 'San Pedro Cusco', 'Maras'],
  'buenos aires': ['Palermo', 'San Telmo', 'Recoleta', 'Puerto Madero', 'Belgrano'],
  'rio de janeiro': ['Copacabana', 'Ipanema', 'Leblon', 'Santa Teresa', 'Barra da Tijuca', 'Botafogo'],
  'sao paulo':    ['Jardins', 'Vila Madelena', 'Pinheiros', 'Moema', 'Itaim Bibi'],
  'santiago':     ['Providencia', 'Las Condes', 'Vitacura', 'Barrio Italia', 'Bellavista'],
  'montevideo':   ['Ciudad Vieja', 'Pocitos', 'Punta Carretas', 'Palermo Montevideo'],
  'quito':        ['Mariscal Sucre', 'La Floresta', 'Historic Center Quito'],
  'guayaquil':    ['Malecon 2000', 'Urdesa', 'Kennedy Norte'],
  'la paz':       ['Sopocachi', 'Miraflores La Paz', 'Zona Sur'],
  'santa cruz':   ['Equipetrol', 'Plan Tres Mil', 'Casco Viejo Santa Cruz'],
  'caracas':      ['Altamira', 'Las Mercedes', 'Chacao'],
  'panama city':  ['Casco Viejo', 'Punta Pacifica', 'Marbella', 'Obarrio'],
  'san jose':     ['Escazu', 'Santa Ana', 'Barrio Amon', 'Alajuela'],
  'guatemala city': ['Zona Viva', 'Antigua Guatemala', 'Zona 10'],
  'asuncion':     ['Recoleta Asuncion', 'Villa Morra', 'Downtown Asuncion'],
  // ── Oceania ──────────────────────────────────────────────────────
  'sydney':       ['CBD', 'Darling Harbour', 'Surry Hills', 'Newtown', 'Bondi', 'Manly', 'Parramatta', 'Glebe', 'Potts Point'],
  'melbourne':    ['CBD', 'Fitzroy', 'St Kilda', 'South Yarra', 'Collingwood', 'Carlton', 'Southbank', 'Richmond'],
  'brisbane':     ['South Bank', 'Fortitude Valley', 'New Farm', 'Paddington Brisbane', 'CBD Brisbane'],
  'gold coast':   ['Surfers Paradise', 'Broadbeach', 'Burleigh Heads', 'Coolangatta', 'Main Beach'],
  'cairns':       ['Cairns City', 'Palm Cove', 'Port Douglas', 'Clifton Beach'],
  'perth':        ['Northbridge', 'Fremantle', 'Subiaco', 'Scarborough'],
  'adelaide':     ['Glenelg', 'North Adelaide', 'Norwood'],
  'auckland':     ['CBD Auckland', 'Ponsonby', 'Parnell', 'Newmarket', 'Takapuna'],
  'queenstown':   ['Queenstown Central', 'Frankton', 'Arrowtown', 'Wanaka'],
  'christchurch': ['Central City', 'Sydenham', 'Riccarton'],
  'rotorua':      ['Rotorua City', 'Ohinemutu', 'Ngongotaha'],
  'wellington':   ['Te Aro', 'Lambton Quay', 'Cuba Street', 'Thorndon'],
  'darwin':       ['Darwin CBD', 'Mindil Beach', 'Fannie Bay'],
  'hobart':       ['Salamanca', 'Battery Point', 'Sandy Bay'],
  'fiji':         ['Suva', 'Nadi', 'Coral Coast', 'Mamanuca Islands', 'Yasawa Islands'],
  'bora bora':    ['Bora Bora Village', 'Matira Beach', 'Vaitape'],
  'tahiti':       ['Papeete', 'Punaauia', 'Moorea'],
  'samoa':        ['Apia', 'Lalomanu', 'Savaii'],
};
